#!/usr/bin/env python3
"""PreToolUse/Bash hook: refuse a `gh issue close` (or either `gh api` equivalent)
that carries no well-formed `## Closing record`.

See ADR-0002 (the rule this enforces), ADR-0005 (this mechanism, every axis and
exit path), ADR-0011 (who produces the record — a dispatched checker, never this
hook), and ADR-0012 (why every deny below carries a systemMessage as well as a
permissionDecisionReason). The shell-quote span scanner is `_hook.quoted_spans()` (#106).

**Stands down where the repo checks in its own copy of this file.** A repo that ships
`.claude/hooks/close-gate.py` registers it as its own PreToolUse hook, so the close is
already judged once — in the agent's turn, at the workstation and inside every stage on a
runner alike. Two enforcers of one rule drift (collod873/claude-workflow#55 found exactly
that against the `issues.closed` gate this replaces), and the cure is one *file*, not one
venue: the repo's copy is this file, so `ships_repo_gate()` stands down for a copy that is
not the one running. The rule cannot drift from itself.

**A non-delivery close is out of scope**, wherever this runs. `--reason "not planned"` and
`--reason duplicate` withdraw the delivery claim, so there is nothing for a record to be
about — the ADR-0013 scope rule, which used to live only in the tracker-side gate and was
the one axis on which these two copies had actually drifted.

The marker: a comment — or the close command's own `--comment` text — whose
first line is `## Closing record`. Most recent wins; since a close command's own
`--comment` would land after any existing comment, it is treated as the winner
whenever it parses as a record at all.

Under that heading, the gate's whole question is count and presence — never
shape (#163 retired the freehand grammar that used to judge it, #168 deleted
the dead code outright; a record generated by `close-ticket` cannot be
malformed, so there is nothing left for a parser to judge):
  - `No diff.`            -> allowed only when the issue body declares no
                             acceptance criteria at all. A body that carries
                             criteria cannot be closed on `No diff.` — that
                             form stands only for a ticket that never needed
                             one.
  - a `base..head` range  -> the issue body has `## Acceptance criteria` with
                             >=1 `- [ ]`; the record's bullet count equals the
                             criterion count, one bullet per criterion in body
                             order. Nothing about a bullet's content is read —
                             an `UNVERIFIED` bullet counts exactly like a `MET`
                             one, because no verdict token is parsed or judged
                             here at all.
  - `Superseded by #<n>`  -> presence only: the line stands alone, and (when
                             the body carries criteria) the bullet count still
                             matches. No disposition is read per bullet and no
                             successor-state lookup happens here — verifying
                             that `#<n>` resolves and is open is `close-ticket
                             --superseded-by`'s job, at generation time, not
                             this gate's at read time.
  - neither               -> deny.

The range must stand on its own line, not as a list item — a leading `- `
before it would be miscounted as a bullet, and standing alone is also what
lets either side be any git revspec (a sha, a ref, a tag, a slashed branch
name) without stray prose in a bullet passing for a range.

Declared ceiling — read before relying on this:
  - A record with the right bullet count passes regardless of what the
    bullets say. That used to mean "a well-shaped lie passes"; count-and-
    presence widens it to "any lie of the right length passes" — the trade
    this gate makes deliberately, because the record is generated by
    `close-ticket` from an exit status it observed, not typed freehand by a
    model with something to prove. Freshness and truth of the underlying
    check are `close-ticket`'s problem, never this hook's.
  - Closes from the GitHub web UI, a phone, or a `Closes #N` merge keyword
    never reach it — this only binds Bash commands on this machine.
  - It is not a lock. No permission rule backs it, and none can: any rule wide
    enough to catch the `gh api` bypass would also break the sub-issue and
    dependency APIs the tracker requires.
  - Failing closed is only true while the hook is alive to refuse. The harness
    kills a `command` hook at its registered `timeout` and treats the kill as a
    non-blocking error, so an over-budget fire lets the close through — a
    fail-open wearing this gate's fail-closed clothes, arriving exactly when
    GitHub or the disk is slow. The deadlines below are therefore a budget, not
    four independent numbers: their worst-case sum (`derive_repo` +
    `repo_toplevel`, memoised to one call + `gh issue view`) must stay under the
    `timeout` this hook is registered with in `settings.json`.
    `hooks/test_close_gate.py` asserts that sum against the registered value, so
    adding a fifth subprocess or shortening the deadline fails a test rather
    than quietly converting the gate's failure mode.
  - A command that only *names* a close inside a quoted argument — a grep for
    the phrase, an echo, a commit message describing this gate — is not treated
    as one, so long as it names no issue number either. This is scope, not a
    hole: a quoted close that does name an issue (`bash -c '…'`) really closes
    when the shell runs it and stays gated like any other.

Every path below exits 0. A refusal never rides on `exit 2` — it rides in
stdout JSON as `permissionDecision: "deny"`, carrying both a
`permissionDecisionReason` (Claude's channel) and a `systemMessage` naming this
hook (the human's channel — the one channel N-hook contention on this event
cannot destroy). The pass path emits no `permissionDecision` field at all —
never `allow` — since `allow` would skip the permission prompt and loosen a
layer this hook exists only to tighten.
"""

import functools
import json
import os
import re
import subprocess
from pathlib import Path

import _hook  # puts bin/ on sys.path (#109)
import gh_support  # noqa: E402
import ticket_shape  # noqa: E402

GH_TIMEOUT_SECONDS = 5
GIT_REMOTE_TIMEOUT_SECONDS = 2

# The repo's own copy of this gate. A repo that checks this in wires it as a project
# PreToolUse hook, and that copy judges the close — including inside a runner stage, where
# nothing under `~/` is installed at all.
REPO_GATE_PATH = ".claude/hooks/close-gate.py"

# The tool that writes a body's `## Acceptance criteria` for it. Named in a deny only where
# it exists: this file now also runs from a repo checkout inside a stage on a GitHub-hosted
# runner, where nothing under `~/` is installed, and a refusal whose one instruction is a
# path the reader cannot run is a refusal with no repair.
TICKETIFY_PATH = Path.home() / "bin" / "file-issue"


def write_criteria_hint() -> str:
    """The instruction a deny gives for a body that carries no criteria to count."""
    if TICKETIFY_PATH.is_file():
        return "run `~/bin/file-issue ticketify <n>` to write them"
    return (
        "add an `## Acceptance criteria` heading to the issue body, one `- [ ]` per "
        "checkable claim"
    )


# --- detecting a close, across all three Bash routes -----------------------

ISSUE_CLOSE_RE = re.compile(r"\bgh\s+issue\s+close\b")
API_STATE_CLOSED_RE = re.compile(
    r"\bgh\s+api\b[^\n]*(?:-f|--field)\s+['\"]?state\s*=\s*['\"]?closed\b",
    re.IGNORECASE,
)
API_GRAPHQL_RE = re.compile(r"\bgh\s+api\s+graphql\b")
CLOSE_ISSUE_MUTATION_RE = re.compile(r"\bcloseIssue\b")

ISSUE_NUMBER_FROM_CLOSE_RE = re.compile(
    r"\bgh\s+issue\s+close\s+(?:(?:-R|--repo)(?:\s+|=)\S+\s+)*(\d+)\b"
)
ISSUE_NUMBER_FROM_PATH_RE = re.compile(r"\bissues/(\d+)\b")

# --- the scope rule: only a close claiming a delivery is judged (ADR-0013) ---
# `not planned` and `duplicate` say no work was delivered, so no record can be about
# anything. The spellings differ by route — `gh issue close` takes `not planned`, agents
# routinely type `not-planned`, and the REST field is `not_planned` — so all three
# separators are one character class rather than three literals.
#
# Long `--reason` only, never the `-r` alias: this regex reads the whole command line,
# where a bare `-r` belongs to `grep`, `cp` and `rm` far more often than to `gh`, and a
# match on one of those would wave a real delivery close straight through. The cost of
# skipping it is a `-r "not planned"` close being gated and refused — the safe direction,
# and repairable by spelling the flag out.
NON_DELIVERY_REASON_RE = re.compile(
    r"--reason(?:\s+|=)(['\"]?)(not[ _-]planned|duplicate)\1(?!\S)",
    re.IGNORECASE,
)
API_NON_DELIVERY_REASON_RE = re.compile(
    r"(?:-f|--field|-F|--raw-field)(?:\s+|=)['\"]?state_reason\s*=\s*"
    r"['\"]?(?:not[ _-]planned|duplicate)\b",
    re.IGNORECASE,
)

# --- where the close is aimed -----------------------------------------------
# The hook's payload `cwd` is the session's directory when the tool call *fires*, which is
# not necessarily the repo the close lands in: `-R owner/repo` names another repo outright,
# and `cd <dir> && gh issue close N` moves before `gh` runs while the payload still reports
# the old directory. Verifying against the wrong repo fails closed (deny/`degraded`), so this
# refused valid closes rather than admitting bad ones — but it refused them on every
# cross-repo path, which is the one `/drain` and `/implement` take outside this checkout.
REPO_FLAG_RE = re.compile(r"(?:-R|--repo)(?:\s+|=)(['\"]?)([^\s'\";|&]+)\1")
CD_RE = re.compile(r"\bcd\s+(?:'([^']*)'|\"([^\"]*)\"|([^\s;|&]+))")

# `--comment` argument extraction — single-quoted, double-quoted, and the
# `"$(cat <<'EOF' ... EOF)"` heredoc shape every real close in this repo uses.
COMMENT_HEREDOC_RE = re.compile(
    r"--comment\s+\"\$\(cat\s*<<-?\s*'?(?P<tag>\w+)'?\s*\n(?P<body>.*?)\n\s*(?P=tag)\s*\)\"",
    re.DOTALL,
)
COMMENT_DQUOTE_RE = re.compile(r'--comment\s+"((?:[^"\\]|\\.)*)"', re.DOTALL)
COMMENT_SQUOTE_RE = re.compile(r"--comment\s+'((?:[^'\\])*)'", re.DOTALL)

# --- the closing record itself ----------------------------------------------

RECORD_HEADING = "## Closing record"
# A range side is any git revspec, not just a sha: `close-ticket` records the range it ran
# checks against verbatim, and a drain branch's base is a ref (`main..HEAD`) as often as a sha,
# so demanding hex both sides refused records written exactly as instructed. The widening is
# safe only because the range is anchored to its own line — the position the grammar already
# mandates — so a stray `a..b` inside a bullet cannot satisfy the requirement.
REVSPEC = r"[A-Za-z0-9._/@{}~^+-]+"
RANGE_LINE_RE = re.compile(rf"^[ \t]*`?({REVSPEC})\.\.({REVSPEC})`?[ \t]*$", re.MULTILINE)
BULLET_RE = re.compile(r"^[ \t]*-\s+(.*)$", re.MULTILINE)

REPO_REF = r"[A-Za-z0-9][A-Za-z0-9._-]*/[A-Za-z0-9][A-Za-z0-9._-]*"
# The gate's own presence-only recognition of the third record form (#154, simplified to
# count-and-presence by #163): the line stands alone on its own line, naming a successor.
# Nothing about the bullets beneath it is read here — no disposition, no verdict, no
# successor-state lookup. Verifying that `#<n>` resolves and is open moved to `close-ticket
# --superseded-by`, which generates this line only once it has already checked that.
SUPERSEDED_RE = re.compile(
    rf"^[ \t]*`?Superseded by (?:({REPO_REF}))?#(\d+)`?[ \t]*\.?[ \t]*$", re.MULTILINE)

# The ticket-grammar trio (CRITERIA_HEADING_RE, CRITERIA_ITEM_RE, PATH_LINE_RE) is
# `ticket_shape`'s (#107).


def detect_close_route(command: str) -> str | None:
    if ISSUE_CLOSE_RE.search(command):
        return "issue-close"
    if API_STATE_CLOSED_RE.search(command):
        return "api-state-closed"
    if API_GRAPHQL_RE.search(command) and CLOSE_ISSUE_MUTATION_RE.search(command):
        return "api-graphql"
    return None


def declares_non_delivery(command: str) -> bool:
    """True when the close marks itself `not planned` or `duplicate` (ADR-0013).

    Read unquoted-only, like every other flag this file parses: a reason named inside a
    quoted string is prose about a close, not the close's own argument, and reading it
    would hand any command that merely *mentions* `--reason "not planned"` a way past the
    gate for the real close standing beside it.
    """
    spans = _hook.quoted_spans(command)
    for pattern in (NON_DELIVERY_REASON_RE, API_NON_DELIVERY_REASON_RE):
        if _hook.unquoted_matches(pattern, command, spans):
            return True
    return False


def close_is_only_quoted_prose(command: str) -> bool:
    """True when every token that made this look like a close sits inside a shell quote.

    A command that merely *names* the phrase — a grep for it, an echo, a commit message
    documenting the gate — is not a close, and denying those made the hook hostile to
    ordinary work on an event it holds machine-globally.

    Quoting is never a bypass, because this is consulted only when no issue number appears
    anywhere in the command: `bash -c 'gh issue close 30'` really does close when the shell
    runs it, names its issue, and so stays gated like any other close.
    """
    spans = _hook.quoted_spans(command)
    for pattern in (ISSUE_CLOSE_RE, API_STATE_CLOSED_RE, API_GRAPHQL_RE):
        if _hook.unquoted_matches(pattern, command, spans):
            return False
    return True


def extract_repo_flag(command: str) -> str | None:
    """The `-R owner/repo` / `--repo owner/repo` the close names, if it names one."""
    matches = _hook.unquoted_matches(REPO_FLAG_RE, command)
    return matches[-1].group(2) if matches else None


def effective_cwd(command: str, cwd: str | None) -> str | None:
    """`cwd` as it will stand when `gh` actually runs — the last unquoted `cd` preceding
    the close wins. A directory that does not resolve is ignored rather than passed on:
    handing a bogus path to `subprocess` would surface as `gh-not-found`, reporting a
    missing binary for what is really a missing directory."""
    route = None
    for pattern in (ISSUE_CLOSE_RE, API_STATE_CLOSED_RE, API_GRAPHQL_RE):
        m = pattern.search(command)
        if m and (route is None or m.start() < route):
            route = m.start()
    if route is None:
        return cwd
    target = None
    for m in _hook.unquoted_matches(CD_RE, command):
        if m.start() >= route:
            break
        target = m.group(1) or m.group(2) or m.group(3)
    if not target or target == "-":
        return cwd
    path = os.path.expanduser(target)
    if not os.path.isabs(path):
        if not cwd:
            return cwd
        path = os.path.join(cwd, path)
    return path if os.path.isdir(path) else cwd


def extract_issue_number(command: str) -> int | None:
    m = ISSUE_NUMBER_FROM_CLOSE_RE.search(command)
    if m:
        return int(m.group(1))
    m = ISSUE_NUMBER_FROM_PATH_RE.search(command)
    if m:
        return int(m.group(1))
    return None


def extract_inline_comment(command: str) -> str | None:
    m = COMMENT_HEREDOC_RE.search(command)
    if m:
        return m.group("body")
    m = COMMENT_DQUOTE_RE.search(command)
    if m:
        return m.group(1)
    m = COMMENT_SQUOTE_RE.search(command)
    if m:
        return m.group(1)
    return None


def find_marker_text(text: str | None) -> str | None:
    """If `text`, once stripped, begins with the closing-record heading, return
    everything after that heading line. Else None — no marker here."""
    if text is None:
        return None
    stripped = text.strip()
    if not stripped.startswith(RECORD_HEADING):
        return None
    return stripped[len(RECORD_HEADING):].lstrip("\n")


def most_recent_record(comments: list) -> str | None:
    """Most recent wins: `gh issue view` returns comments oldest-first, so scan
    from the end and take the first (i.e. most recent) that parses as a record."""
    for c in reversed(comments or []):
        body = c.get("body", "") if isinstance(c, dict) else ""
        marker = find_marker_text(body)
        if marker is not None:
            return marker
    return None


def count_body_criteria(body: str) -> int | None:
    """None means the heading itself is missing — a distinct failure from zero
    items under a heading that does exist."""
    if not ticket_shape.CRITERIA_HEADING_RE.search(body):
        return None
    section = ticket_shape.section_text(body, ticket_shape.CRITERIA_HEADING_RE)
    return len(ticket_shape.CRITERIA_ITEM_RE.findall(section))


def _bullet_count_denial(record_text: str, criteria_count: int,
                          close_ticket_stub_text: str = "close-ticket"):
    """The record's bullets, held against the body's criteria count — arithmetic only,
    nothing about what a bullet says.

    Returns `(denial, bullets)`; `denial` is None when the count is right. Shared by every
    record form that carries bullets — the range form and, since #163, the presence-only
    superseded form too — so a criterion cannot be dissolved by writing fewer bullets than
    it names (#154's argument, unaffected by #163: only the per-bullet judgment that used to
    sit on top of this arithmetic is gone, never the count check itself).

    `close_ticket_stub_text` is the filled `close-ticket` invocation the caller
    (`evaluate_record`) has already built (`close_ticket_stub`) — threaded through rather
    than rebuilt here, since only `main()` has the `cwd`/`repo_flag` to fill it. The default
    covers any caller with no live close to fill it from.
    """
    if criteria_count == 0:
        return (
            "deny",
            "missing-acceptance-criteria",
            "the issue body's `## Acceptance criteria` heading has no `- [ ]` items. Plain "
            "`- ` bullets don't count — only `- [ ]` checkbox items do. Neither `No diff.` "
            "nor `Superseded by #<n>` stands in for criteria that were never written: "
            f"{write_criteria_hint()}, then run "
            f"`{close_ticket_stub_text}` to close it.",
        ), []
    bullets = [b.strip() for b in BULLET_RE.findall(record_text) if b.strip()]
    if len(bullets) != criteria_count:
        return (
            "deny",
            "criteria-count-mismatch",
            f"{criteria_count} acceptance criteria in the body but {len(bullets)} "
            "bullets in the closing record — one bullet per criterion, in the body's "
            f"own order. Run `{close_ticket_stub_text}` instead of writing the record by "
            "hand — it generates exactly one bullet per criterion.",
        ), []
    return None, bullets


def evaluate_record(record_text: str, criteria_count: int | None,
                    close_ticket_stub_text: str = "close-ticket") -> tuple[str, str, str]:
    """Return (verdict, reason_code, human_message). verdict in {"allow", "deny"}.

    `close_ticket_stub_text` is a filled `close-ticket` invocation (`close_ticket_stub`),
    threaded through into every denial that used to point at the retired checker template —
    `main()` builds the real one from the live close's `cwd`/`repo_flag`; the default here
    covers any other caller with no close to fill it from.

    Count and presence, never shape (#163): does the record name a range, `No diff.`, or a
    `Superseded by #<n>` successor — and, wherever the body carries criteria, does it carry
    exactly one bullet per criterion? Nothing about a bullet's content is read; an
    `UNVERIFIED` bullet counts exactly like a `MET` one.

    `No diff.` excuses the **range** and nothing else, and only where the body declares no
    criteria at all — see collod873/claude-workflow#60, where the tracker-side copy of this
    grammar closed an issue that had delivered none of its seven criteria on the strength of
    its first two words. A body carrying criteria needs a record naming them, whichever form
    it takes.

    The superseded form no longer looks up its successor's state here — that check moved to
    `close-ticket --superseded-by`, which generates the `Superseded by #<n>` line only once
    it has already verified the successor resolves and is open. This gate reads presence,
    not liveness.
    """
    declares_no_diff = record_text.lstrip().startswith("No diff.")
    superseded = SUPERSEDED_RE.search(record_text)

    if superseded is not None:
        number = int(superseded.group(2))
        if criteria_count is None:
            return ("allow", "superseded",
                    f"superseded by #{number}, and the body declares no criteria.")
        denial, bullets = _bullet_count_denial(record_text, criteria_count, close_ticket_stub_text)
        if denial is not None:
            return denial
        return ("allow", "superseded",
                f"superseded by #{number}, with one bullet per criterion.")

    if declares_no_diff:
        if criteria_count is None:
            return "allow", "no-diff", "No diff. declared, and the body declares no criteria."
        if criteria_count == 0:
            return (
                "deny",
                "missing-acceptance-criteria",
                "the issue body's `## Acceptance criteria` heading has no `- [ ]` items. "
                "Plain `- ` bullets don't count — only `- [ ]` checkbox items do. Neither "
                "`No diff.` nor `Superseded by #<n>` stands in for criteria that were never "
                f"written: {write_criteria_hint()}.",
            )
        return (
            "deny",
            "no-diff-with-criteria",
            "the closing record declares `No diff.` but the issue body carries a `## "
            "Acceptance criteria` heading — `No diff.` stands only for a ticket that never "
            "carried criteria. Run `close-ticket` to verify and record them.",
        )

    if not RANGE_LINE_RE.search(record_text):
        return (
            "deny",
            "no-range-or-no-diff",
            "the closing record declares neither `No diff.`, a `base..head` range "
            "standing alone on its own line, nor `Superseded by #<n>` — a range written "
            f"as a bullet doesn't count. Run `{close_ticket_stub_text}` instead of "
            "writing the record by hand.",
        )

    if criteria_count is None:
        return (
            "deny",
            "missing-acceptance-criteria",
            "the issue body has no `## Acceptance criteria` heading. If this ticket truly "
            "carries no commit, post a `## Closing record` comment declaring `No diff.`; "
            f"otherwise {write_criteria_hint()}, then run "
            f"`{close_ticket_stub_text}` to close it.",
        )

    denial, bullets = _bullet_count_denial(record_text, criteria_count, close_ticket_stub_text)
    if denial is not None:
        return denial

    return "allow", "met", "one bullet per criterion, in the body's own order."


# --- environment: gh resolution, repo, the gh call --------------------------


def derive_repo(cwd: str | None) -> str:
    if not cwd:
        return ""
    try:
        result = subprocess.run(
            ["git", "-C", cwd, "remote", "get-url", "origin"],
            capture_output=True, text=True, timeout=GIT_REMOTE_TIMEOUT_SECONDS,
        )
    except (OSError, subprocess.TimeoutExpired):
        return ""
    if result.returncode != 0:
        return ""
    m = re.search(r"[:/]([^/:]+/[^/]+?)(?:\.git)?\s*$", result.stdout.strip())
    return m.group(1) if m else ""


@functools.lru_cache(maxsize=None)
def repo_toplevel(cwd: str | None) -> Path | None:
    """The working tree's root, or None when `cwd` is not a repo or git won't answer.

    The one place this hook shells out to git for it. Two callers want it for different
    reasons — the repo-gate probe below reads a file relative to it, and
    `close_ticket_stub` hands it over as the `close-ticket` invocation's `<checkout>` —
    and neither is allowed to fail loudly: a hook that raised here would refuse closes
    over a slow disk.

    Memoised because those two callers ask the same question about the same `cwd` within
    one fire, and each miss costs a `GIT_REMOTE_TIMEOUT_SECONDS` deadline. That mattered:
    this hook is registered with a wall-clock `timeout` in settings.json, and the sum of
    its worst-case subprocess deadlines — `derive_repo` + two `repo_toplevel` calls +
    `gh issue view` — used to exceed it. A hook the harness kills mid-flight is a
    non-blocking error, so the tool proceeds: the one gate on this machine that
    deliberately fails *closed* would have failed **open**, and only when GitHub or the
    disk was slow, which is exactly when nobody is watching. One process per fire, and the
    budget fits under the registered deadline with room to spare.
    """
    if not cwd:
        return None
    try:
        result = subprocess.run(
            ["git", "-C", cwd, "rev-parse", "--show-toplevel"],
            capture_output=True, text=True, timeout=GIT_REMOTE_TIMEOUT_SECONDS,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    if result.returncode != 0:
        return None
    return Path(result.stdout.strip())


def ships_repo_gate(cwd: str | None) -> bool:
    """Whether the repo containing `cwd` checks in its own copy of this gate — and that
    copy is a different file from the one now running.

    The second half is what lets one file serve both venues. The machine-global hook and
    the repo's checked-in copy are the same source; without the identity test the repo's
    copy would find itself, stand down, and leave the close ungated — a fail-open dressed
    up as deduplication. `.resolve()` on both sides because the machine-global copy runs
    through a `~/.claude/hooks/` symlink (ADR-0019).

    Read off the working tree rather than the remote: the file being present in the
    checkout is what makes the repo's copy this repo's rule, and a hook that asked GitHub
    would fail open on every network hiccup — the one shape this gate must not have. A
    tree that is not a repo, or a `git` that will not answer, returns False and the hook
    judges the close itself.
    """
    top = repo_toplevel(cwd)
    if top is None:
        return False
    gate = top / REPO_GATE_PATH
    return gate.is_file() and gate.resolve() != Path(__file__).resolve()


def close_ticket_stub(issue_number, cwd: str | None, repo_flag: str | None) -> str:
    """The `close-ticket` invocation a refusal hands over, filled as far as this hook
    can fill it — closing's mirror of `~/bin/file-issue`'s pointer for `gh issue create`
    (`validate-bash.py:93`), and the same shape a prior `checker_stub` (539a39e) proved
    out for the checker dispatch this script retires (#160).

    `<base>..<head>` stays a placeholder: the operator's own commits are not visible to
    this hook. The checkout is this repo's own toplevel, resolved from `cwd` — unless the
    close named a `-R other/repo`, where the local toplevel is not that repo's tree and
    handing it over would point `close-ticket` at the wrong checkout; saying so beats
    guessing one.

    The tool's own path is resolved the same way, and for the same reason
    `write_criteria_hint()` resolves `~/bin/file-issue`: a bare `bin/close-ticket` runs
    only where the checkout vendors one, and `~/.agents/skills/bin/close-ticket` names a
    directory that does not exist inside a stage on a GitHub-hosted runner (#185). Naming
    whichever one is actually there is the only form that is a repair at both venues.
    """
    checkout = repo_toplevel(cwd)
    if checkout is not None and not repo_flag:
        checkout_value = str(checkout)
    else:
        checkout_value = "<a checkout of this repo at the range's head>"
    vendored = checkout is not None and (checkout / "bin" / "close-ticket").is_file()
    tool = "bin/close-ticket" if vendored else "~/.agents/skills/bin/close-ticket"
    repo_arg = f" --repo {repo_flag}" if repo_flag else ""
    return f"{tool} {issue_number} <base>..<head> {checkout_value}{repo_arg}"


def fetch_issue(gh_path: str, cwd: str | None, issue_number: int,
                repo: str | None = None) -> tuple[str, list, str | None]:
    """Return (body, comments, error_reason). error_reason is None on success.

    `repo`, when the close named one, is carried through to `gh` so the issue is read from
    the repo the close actually targets — `gh`'s own precedence, where `-R` outranks cwd."""
    gh = gh_support.bind_gh(gh_path, repo, timeout=GH_TIMEOUT_SECONDS)
    try:
        result = gh("issue", "view", str(issue_number), "--json", "body,comments",
                    cwd=cwd, capture_output=True, text=True)
    except subprocess.TimeoutExpired:
        return "", [], "gh-timeout"
    except OSError:
        return "", [], "gh-not-found"
    if result.returncode != 0:
        return "", [], "gh-error"
    try:
        data = json.loads(result.stdout)
    except json.JSONDecodeError:
        return "", [], "gh-bad-response"
    return data.get("body", "") or "", data.get("comments", []) or [], None


# --- observability -----------------------------------------------------------


def _row(payload: dict, repo: str, issue_number, verdict: str, reason: str,
         gh_path: str) -> None:
    """One JSONL run row through the machine's single writer (#182).

    This used to be a private seven-column TSV of its own beside `~/.claude/` — its own
    timestamp format, no rotation, no retention, 950 rows and growing, and a hand-written
    exemption in `bin/lint` and `_hook.py` holding the "one log shape" rule open for it.
    The columns survive verbatim as fields (`repo`, `issue`, `reason`, `gh`); what changes
    is that they now sit beside every other mechanism's rows, under one prune, where
    `bin/hook-report` can count them without knowing this hook exists. The old TSV is left
    on disk as an archive, not migrated — anything in it worth keeping past 30 days belongs
    in `docs/research/`, which is the rule `_hook.LOG_RETENTION_DAYS` states.

    Verdicts: `allow` · `deny` · `degraded`. `reason` stays the slug it always was, so a
    30-day count per refusal reason is one field away."""
    _hook.append_log(_hook.HOOK_NAME, _hook.run_row(
        payload, verdict,
        repo=repo or "",
        issue=issue_number,
        reason=reason,
        gh=gh_path or "",
    ))


def deny(payload: dict, repo: str, issue_number, reason: str, gh_path: str,
         human_message: str, verdict: str = "deny") -> None:
    _row(payload, repo, issue_number, verdict, reason, gh_path)
    _hook.deny(human_message)


def allow(payload: dict, repo: str, issue_number, reason: str, gh_path: str) -> None:
    _row(payload, repo, issue_number, "allow", reason, gh_path)
    # Silent — never `permissionDecision: "allow"`. No stdout at all.


def main() -> None:
    resolved_gh = gh_support.gh_bin()

    payload, ok = _hook.read_payload()
    if not ok:
        _row(payload, "", None, "allow", "unparseable-stdin", resolved_gh or "")
        return

    cwd = payload.get("cwd")
    tool_input = payload["tool_input"]  # _hook.read_payload() guarantees a dict

    command = tool_input.get("command")
    if not isinstance(command, str) or not command.strip():
        _row(payload, "", None, "allow", "unparseable-stdin", resolved_gh or "")
        return

    route = detect_close_route(command)
    if route is None:
        return  # Not a close at all — fully silent, no log row.

    issue_number = extract_issue_number(command)
    if issue_number is None and close_is_only_quoted_prose(command):
        # Names a close without invoking one. Logged rather than silent: a near-miss on a
        # machine-global gate is worth being able to audit after the fact.
        _row(payload, "", None, "allow", "close-mentioned-not-invoked", resolved_gh or "")
        return

    # The repo actually verified against, not merely the one the session happened to sit in.
    repo_flag = extract_repo_flag(command)
    gh_cwd = effective_cwd(command, cwd)
    cwd_repo = derive_repo(gh_cwd)
    repo = repo_flag or cwd_repo

    # A repo that checks in its own copy of this file owns this judgement, and the
    # machine-global copy stands down there rather than judging the same close twice. The
    # repo's copy never stands down for itself — `ships_repo_gate` compares the file it
    # finds against the one running — so exactly one of the two decides, and because they
    # are the same source there is no second rule to drift.
    #
    # Only when the close targets the repo the session is sitting in: a `-R other/repo` close
    # is judged by this hook as before, since the tree under `cwd` says nothing about the gate
    # that repo does or does not ship. Logged rather than silent — this estate counts what its
    # gates do, and a stand-down that left no row would be indistinguishable from a pass.
    if repo_flag in (None, "", cwd_repo) and ships_repo_gate(gh_cwd):
        _row(payload, repo, issue_number, "allow", "repo-gate-owns-repo",
             resolved_gh or "")
        return

    # ADR-0013's scope rule, now that this gate is the only one left to hold it: a close
    # marked `not planned` or `duplicate` withdraws the delivery claim, so there is nothing
    # for a record to be about and refusing one would be the gate overruling a decision
    # rather than verifying a claim. Judged before the issue is fetched — the reason is on
    # the command line, and a scope rule that spent a network call would be paying to learn
    # it has nothing to do.
    if declares_non_delivery(command):
        _row(payload, repo, issue_number, "allow", "non-delivery-close",
             resolved_gh or "")
        return

    if issue_number is None:
        deny(payload, repo, None, "unparseable-issue-number", resolved_gh or "",
             "could not parse an issue number from this close command.")
        return

    stub_text = close_ticket_stub(issue_number, gh_cwd, repo_flag)

    inline_record = find_marker_text(extract_inline_comment(command))

    # There is no longer a fast path for an inline `No diff.`. It used to allow here
    # without a network call, which meant a close could skip the criteria check simply by
    # declaring `No diff.` on its own command line — the same hole as the one in
    # `evaluate_record`, one step earlier and cheaper to reach. Counting the issue's
    # criteria requires reading the issue, so the call is not optional.

    if resolved_gh is None:
        deny(payload, repo, issue_number, "gh-not-found", "",
             "gh is not resolvable on this machine — cannot verify, so the close is refused.",
             verdict="degraded")
        return

    body, comments, fetch_err = fetch_issue(resolved_gh, gh_cwd, issue_number, repo_flag)
    if fetch_err:
        deny(payload, repo, issue_number, fetch_err, resolved_gh,
             f"could not verify against GitHub ({fetch_err}) — failing closed.",
             verdict="degraded")
        return

    record_text = inline_record if inline_record is not None else most_recent_record(comments)
    if record_text is None:
        deny(payload, repo, issue_number, "no-closing-record", resolved_gh,
             "no `## Closing record` found — neither on the close command's own "
             "--comment nor as an issue comment. Run close-ticket instead — it verifies "
             f"the criteria, posts the record, and closes in one step:\n\n    {stub_text}"
             "\n\nOr if this ticket truly carries no commit, post a `## Closing record` "
             "comment declaring `No diff.`")
        return

    criteria_count = count_body_criteria(body)
    verdict, reason, message = evaluate_record(record_text, criteria_count, stub_text)
    if verdict == "allow":
        allow(payload, repo, issue_number, reason, resolved_gh)
    else:
        deny(payload, repo, issue_number, reason, resolved_gh, message)


if __name__ == "__main__":
    main()
