import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { frontmatterBlock } from "./adr-frontmatter";

export const ADR_DIR = "docs/adr";
export const INDEX_RELATIVE_PATH = `${ADR_DIR}/INDEX.md`;

const LANDED_RE = /^(\d{4})-(.+)\.md$/;
const H1_RE = /^#[ \t]+(.+?)[ \t]*$/m;

const INDEX_HEADER = `<!-- Generated by \`bin/adr-check\`. Edits here are overwritten; change the ADR. -->
# Decisions

Every constraint this repo is bound by, newest last. An ADR records something later
work must not stray from; the title is the ruling. Read a body only for the why.

File one with \`new-adr "the ruling as a sentence"\`, then \`new-adr --land <draft>\`.

| # | Ruling | Status |
|---|---|---|
`;

export interface AdrFile {
  name: string;
  content: string;
}

interface Entry {
  number: number;
  name: string;
  title: string;
  status: string;
  words: number;
}

function statusOf(content: string): string {
  const block = frontmatterBlock(content);
  if (block === undefined) return "?";
  for (const line of block.split("\n")) {
    if (line.trimStart().startsWith("#") || !line.includes(":")) continue;
    const [key, ...rest] = line.split(":");
    if (key.trim() === "status") return rest.join(":").trim() || "?";
  }
  return "?";
}

function bodyOf(content: string): string {
  const match = /^---\n[\s\S]*?\n---\n/.exec(content);
  return match ? content.slice(match[0].length) : content;
}

function entryOf(file: AdrFile): Entry | undefined {
  const named = LANDED_RE.exec(file.name);
  if (!named) return undefined;

  const body = bodyOf(file.content);
  const titled = H1_RE.exec(body);
  return {
    number: Number(named[1]),
    name: file.name,
    title: titled ? titled[1].trim() : "",
    status: statusOf(file.content),
    words: body.replace(H1_RE, "").split(/\s+/).filter(Boolean).length,
  };
}

export function renderAdrIndex(files: AdrFile[]): string {
  const corpus = files
    .map(entryOf)
    .filter((entry): entry is Entry => entry !== undefined)
    .sort((left, right) => left.number - right.number);

  const rows = corpus.map((entry) => {
    const ruling = entry.title.replaceAll("|", "\\|") || `_(untitled: ${entry.name})_`;
    return `| ${String(entry.number).padStart(4, "0")} | [${ruling}](${entry.name}) | ${entry.status} |`;
  });

  const counts = new Map<string, number>();
  for (const entry of corpus) counts.set(entry.status, (counts.get(entry.status) ?? 0) + 1);
  const tally = [...counts.entries()]
    .sort(([left], [right]) => (left < right ? -1 : left > right ? 1 : 0))
    .map(([status, count]) => `${count} ${status}`)
    .join(" · ");

  const words = corpus.reduce((total, entry) => total + entry.words, 0);
  const noun = corpus.length === 1 ? "ADR" : "ADRs";
  const footer = `\n${corpus.length} ${noun} · ${tally} · ${words.toLocaleString("en-US")} words total.\n`;

  return INDEX_HEADER + rows.join("\n") + "\n" + footer;
}

export function adrCorpus(repoRoot: string): AdrFile[] {
  let names: string[];
  try {
    names = readdirSync(join(repoRoot, ADR_DIR));
  } catch {
    return [];
  }

  return names
    .filter((name) => LANDED_RE.test(name))
    .map((name) => ({ name, content: readFileSync(join(repoRoot, ADR_DIR, name), "utf8") }));
}

export function regenerateAdrIndex(repoRoot: string): boolean {
  const index = join(repoRoot, INDEX_RELATIVE_PATH);
  if (!existsSync(index)) return false;

  try {
    const files = adrCorpus(repoRoot);
    if (files.length === 0) return false;

    writeFileSync(index, renderAdrIndex(files));
    return true;
  } catch {
    return false;
  }
}
