import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { FORMATS } from "@jscpd/tokenizer";
import { childEnv } from "./child-env.ts";

/**
 * The clone gate (`docs/agents/clone-gate.md`), jscpd behind a runner that owns the four rules
 * jscpd itself has no opinion about.
 *
 * The detector is the easy half. What makes a gate worth having is that **a passing run cannot
 * mean "I read nothing"** — so this file re-derives its own scope on every run rather than
 * trusting a list somebody wrote once:
 *
 * - the file set is `git ls-files` from the root, so a new directory is in scope the moment it
 *   exists (rule 1) — the failure the doc records is a hand-kept root list that never gained
 *   `bin/`;
 * - the `--format` list is derived from the extensions actually present, looked up in jscpd's own
 *   `FORMATS` table, never typed here (rule 2);
 * - every file that survives the path rules is bucketed before the scan, and an undeclared bucket
 *   **refuses the run** rather than being skipped (rule 3), as does any file jscpd silently
 *   declined to read — its `maxSize` default is exactly the kind of quiet hole this catches;
 * - the banner prints how many files were actually scanned (rule 4).
 *
 * Rule 5 is `clone-gate.baseline.json`: written once, at turn-on, over the 98 clones this repo
 * already had, and it only ever shrinks — a clone that stops reproducing is a finding here until
 * its baseline entry is deleted.
 *
 * Rule 6 is where it runs: the `test` and `all` slots of `.claude/contract.json` and CI, never the
 * `stop` slot. This repo's `stop` slot is `bin/gauntlet stop`, which runs the `test` slot — so the
 * gauntlet exports `GAUNTLET_VENUE` and this file declines when it sees it. The gauntlet does not
 * schedule the clone gate at any venue; `npm run check` and `.github/workflows/verify.yml` do,
 * exactly once each.
 */

/** Where the ratchet lives, relative to the repo root. */
export const BASELINE_RELATIVE_PATH = ".Workflow/agent-workflows/shared/clone-gate.baseline.json";

/**
 * jscpd's own defaults for what counts as a clone, restated here so the numbers are decisions this
 * repo made rather than ones it inherited and would never notice changing.
 */
const MIN_TOKENS = 50;
const MIN_LINES = 5;

/**
 * jscpd's two size heuristics, both raised past anything this repo holds. Their defaults — 1000
 * lines and 100kb — drop a file from the scan *and from the report*, which is the exact shape rule
 * 3 exists to catch: turning the gate on here, `session-capture.test.ts` (1035 lines) vanished from
 * a green run. Raised rather than removed because a genuinely enormous file is worth an explicit
 * exclusion, not a silent one.
 */
const MAX_LINES = 100_000;
const MAX_SIZE = "8mb";

/**
 * Where a file whose language its name does not carry is copied for the scan. Inside the repo, not
 * `os.tmpdir()`: jscpd resolves its inputs against the working directory and silently drops a path
 * outside it. Deleted after every run, and excluded from scope so a killed run's leftovers can
 * never enter the next one.
 */
const SCAN_DIR = ".clone-gate-scan";

/**
 * Paths left out of the scan. Rule 1 allows an exclusion and requires the reason to sit next to
 * the pattern — not in a commit message, not in someone's memory. A path matches when it is the
 * entry itself or lives under it.
 */
const EXCLUDED_PATHS: ReadonlyArray<{ path: string; why: string }> = [
  {
    path: "package-lock.json",
    why: "npm's generated lockfile. Its repetition is the format's, not this repo's — nobody refactors it, and a finding there could only ever be noise.",
  },
  {
    path: ".Workflow/agent-workflows/watchdog/adr-corpus.evidence.json",
    why: "generated by `generate-corpus-fixture.ts` from docs/adr and docs/research, and gated by its own `regenerate && diff` in `bin/gauntlet push`. Duplication in it is duplication in the sources it was generated from, counted twice.",
  },
  {
    path: BASELINE_RELATIVE_PATH,
    why: "this gate's own output. Its entries are structurally alike by construction, so scanning it would eventually have the gate reporting itself.",
  },
  {
    path: SCAN_DIR,
    why: "this gate's own scratch copies (see `stageForScan`). Deleted after every run; excluded so a killed run's leftovers can never be scanned as if they were source.",
  },
];

/**
 * Extensions present in the tree that the gate does not read, each with the reason. Rule 2: leaving
 * code out of scope is allowed; doing it silently is not. Anything present and named by neither
 * this list nor a jscpd format refuses the run.
 */
const IGNORED_EXTENSIONS: ReadonlyArray<{ ext: string; why: string }> = [
  {
    ext: "gitignore",
    why: "a list of path patterns. It has no lexical structure to tokenise, and the only 'duplication' it can hold is two patterns spelled alike, which is not a refactor.",
  },
  {
    ext: "txt",
    why: "plain prose fixtures. jscpd ships a `txt` format but tokenises nothing from them, so declaring the extension is the honest form of what the scan would do anyway.",
  },
];

/**
 * Files whose language nothing inside them states. Rule 2 is satisfied by declaring the language,
 * not only by declining to read it — a file this repo can run belongs in the scan, and dropping it
 * because its name is uninformative is how `bin/` went uncovered in the failure the doc records.
 */
const PATH_FORMATS: ReadonlyArray<{ path: string; format: string; why: string }> = [
  {
    path: ".husky/pre-push",
    format: "bash",
    why: "husky v9 sources its hooks rather than executing them, so they carry neither a shebang nor an extension. git runs this as a shell script; nothing in the file says so.",
  },
];

/**
 * Interpreters a shebang can name, and the jscpd format that reads that language. This is what
 * keeps `bin/gauntlet`, `bin/new-adr` and `bin/close-ticket` in scope: jscpd resolves a format from
 * the file extension alone, and every one of those files has none. They are copied under a
 * synthetic extension for the scan (see `stageForScan`) and reported under their real path.
 */
const SHEBANG_FORMATS: Readonly<Record<string, string>> = {
  bash: "bash",
  sh: "bash",
  zsh: "bash",
  python: "python",
  python3: "python",
  node: "javascript",
};

/** One file the gate will scan, and how it resolved that file's language. */
interface ScopedFile {
  /** Repo-relative path, as `git ls-files` and every report line spell it. */
  path: string;
  /** The jscpd format that reads it. */
  format: string;
  /** The extension jscpd needs to see to pick that format — supplied by us for a shebang file. */
  ext: string;
  /** True when the format came from a shebang rather than the file's own extension. */
  staged: boolean;
}

/** Extension → jscpd format, inverted from jscpd's own table so it cannot go stale against it. */
function extensionFormats(): Map<string, string> {
  const byExt = new Map<string, string>();
  for (const [format, { exts }] of Object.entries(FORMATS)) {
    for (const ext of exts) if (!byExt.has(ext)) byExt.set(ext, format);
  }
  return byExt;
}

/** A path's extension, lowercased, or `""` for a file whose name carries none. */
function extensionOf(path: string): string {
  const name = path.slice(path.lastIndexOf("/") + 1);
  const dot = name.lastIndexOf(".");
  // A leading dot is a name, not an extension: `.gitignore` is `gitignore`, `.env.example` is
  // `example`. Anything else with no dot at all buckets as `""`, the shebang case.
  return dot > 0 ? name.slice(dot + 1).toLowerCase() : name.startsWith(".") ? name.slice(1).toLowerCase() : "";
}

/** How many lines a file holds — asked only about the files jscpd left out of its report. */
function lineCount(absolutePath: string): number {
  try {
    return readFileSync(absolutePath, "utf8").split("\n").length;
  } catch {
    return 0;
  }
}

/** The interpreter a `#!` line names, by basename, or `undefined` when there is no shebang. */
function shebangInterpreter(absolutePath: string): string | undefined {
  let head: string;
  try {
    head = readFileSync(absolutePath, "utf8").slice(0, 200).split("\n", 1)[0] ?? "";
  } catch {
    return undefined;
  }
  if (!head.startsWith("#!")) return undefined;
  const words = head.slice(2).trim().split(/\s+/);
  // `#!/usr/bin/env bash` names the interpreter in the second word; `#!/bin/bash` in the first.
  const named = words[0]?.endsWith("/env") ? words[1] : words[0];
  return named?.slice(named.lastIndexOf("/") + 1);
}

/**
 * Every file the repo tracks or has newly written, from the root. `--others --exclude-standard`
 * is what puts a file that is not committed yet in scope: new code is exactly when a clone is
 * cheapest to not write.
 *
 * `childEnv()` because `GIT_DIR` beats a cwd, and this runs downstream of hooks that export it.
 */
function repoFiles(root: string): string[] {
  const out = execFileSync("git", ["ls-files", "-z", "--cached", "--others", "--exclude-standard"], {
    cwd: root,
    env: childEnv(),
    encoding: "utf8",
    maxBuffer: 32 * 1024 * 1024,
  });
  return out.split("\0").filter((path) => path.length > 0);
}

/**
 * True for the one entry shape `git ls-files` uses that is not a file: a **nested git repository**,
 * reported as its directory with a trailing slash — `knowledge-base/` — because everything inside
 * it belongs to *that* repository's index, not this one's. CI checks the private corpus repo out
 * there (`audit.yml`), so the entry exists on the runner and nowhere else, which is how every local
 * gauntlet stayed green while the Audit lane's `pre-push` died on a refusal (#218).
 *
 * It is not enough to trust the slash. A directory that is not a repository would be a real gap in
 * scope, and letting it through on punctuation alone is exactly the silent skip rule 3 forbids — so
 * the entry has to actually carry a `.git`, and anything else with a trailing slash still lands in
 * `undeclared` and still refuses the run.
 */
function isNestedRepository(root: string, path: string): boolean {
  return path.endsWith("/") && existsSync(join(root, path, ".git"));
}

/** What bucketing the tree produced: what will be scanned, and what nothing accounts for. */
interface Scope {
  files: ScopedFile[];
  /** Extension → the files nothing declares. The refusal in rule 3 is built from this. */
  undeclared: Map<string, string[]>;
  /**
   * Nested repositories skipped, in `git ls-files` spelling. Named in the banner rather than
   * dropped: rule 3's whole point is that a skip nobody can see reads the same as a clean scan.
   */
  nested: string[];
}

/**
 * Buckets every file under `root` into scanned, excluded, ignored, or undeclared. This is the
 * self-audit half of rule 3, and it runs *before* the scan so a repo that grew a language gets a
 * refusal rather than a number that quietly stopped covering it.
 */
export function scopeOf(root: string): Scope {
  const byExt = extensionFormats();
  const ignored = new Set(IGNORED_EXTENSIONS.map((entry) => entry.ext));
  const files: ScopedFile[] = [];
  const undeclared = new Map<string, string[]>();
  const nested: string[] = [];

  for (const path of repoFiles(root)) {
    if (EXCLUDED_PATHS.some((entry) => path === entry.path || path.startsWith(`${entry.path}/`))) continue;
    if (isNestedRepository(root, path)) {
      nested.push(path);
      continue;
    }
    const ext = extensionOf(path);
    const byExtension = byExt.get(ext);
    if (byExtension && !ignored.has(ext)) {
      files.push({ path, format: byExtension, ext, staged: false });
      continue;
    }
    if (ignored.has(ext)) continue;
    const interpreter = shebangInterpreter(join(root, path));
    const declared = PATH_FORMATS.find((entry) => entry.path === path)?.format;
    const byShebang = declared ?? (interpreter === undefined ? undefined : SHEBANG_FORMATS[interpreter]);
    if (byShebang) {
      files.push({ path, format: byShebang, ext: FORMATS[byShebang]?.exts[0] ?? ext, staged: true });
      continue;
    }
    const bucket = undeclared.get(ext) ?? [];
    bucket.push(path);
    undeclared.set(ext, bucket);
  }

  files.sort((a, b) => a.path.localeCompare(b.path));
  nested.sort((a, b) => a.localeCompare(b));
  return { files, undeclared, nested };
}

/**
 * Rule 3's message. It names each undeclared bucket, its file count, an example path, and *both*
 * ways to resolve it — because the failure mode this replaces is someone reaching for whichever
 * one the error happened to mention.
 */
function refusal(undeclared: Map<string, string[]>): string {
  const lines = [
    "clone gate: refusing to scan — these files are covered by neither a format nor an ignore rule.",
    "A bucket nothing declares is a bucket the gate would have skipped silently, and a silent skip",
    "is indistinguishable from a clean scan (docs/agents/clone-gate.md, rule 3).",
    "",
  ];
  for (const [ext, paths] of [...undeclared].sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(`  .${ext || "(no extension)"} — ${paths.length} file(s), e.g. ${paths[0]}`);
  }
  lines.push(
    "",
    "Resolve each bucket one of two ways, in .Workflow/agent-workflows/shared/clone-gate.ts:",
    "  - scan it: give the language a jscpd format (or a SHEBANG_FORMATS entry, for a file whose",
    "    language its name does not carry);",
    "  - or don't: add the extension to IGNORED_EXTENSIONS with the reason it is out of scope.",
  );
  return lines.join("\n");
}

/**
 * jscpd picks a file's language from its extension and has no per-file override, so a shebang
 * script with no extension is unreadable to it. Those files are copied into a scratch tree under
 * the extension their language uses, and the copy's path maps back to the real one for every
 * report line. Returns the scratch directory (to delete) and that mapping.
 */
function stageForScan(root: string, files: ScopedFile[]): { dir: string; scanPath: Map<string, string> } {
  const dir = join(root, SCAN_DIR);
  rmSync(dir, { recursive: true, force: true });
  mkdirSync(dir, { recursive: true });
  const scanPath = new Map<string, string>();
  for (const file of files) {
    if (!file.staged) {
      scanPath.set(resolve(root, file.path), file.path);
      continue;
    }
    const staged = join(dir, `${file.path.replace(/\//g, "__")}.${file.ext}`);
    copyFileSync(join(root, file.path), staged);
    scanPath.set(resolve(staged), file.path);
  }
  return { dir, scanPath };
}

/** One duplicated fragment jscpd found, in the two shapes this file needs it in. */
interface Duplicate {
  /** Stable across line movement and file renames: the fragment's own content, plus its language. */
  hash: string;
  format: string;
  lines: number;
  tokens: number;
  /** Repo-relative, for a human reading the failure. Never part of `hash`. */
  where: string[];
}

/** One baseline entry — a `Duplicate` minus nothing, so a stale entry is readable on its own. */
type BaselineEntry = Duplicate;

interface JscpdReport {
  statistics: { formats: Record<string, { sources: Record<string, unknown> }> };
  duplicates: Array<{
    format: string;
    fragment: string;
    lines: number;
    tokens: number;
    firstFile: { name: string; start: number };
    secondFile: { name: string; start: number };
  }>;
}

/** What one scan measured: the clones, and every file jscpd confirmed it actually read. */
interface ScanResult {
  duplicates: Duplicate[];
  analyzed: Set<string>;
}

function fingerprint(format: string, fragment: string): string {
  return createHash("sha256").update(`${format}\0${fragment}`).digest("hex").slice(0, 16);
}

/** Runs jscpd over exactly the scoped files and reads its JSON report back. */
function scan(root: string, files: ScopedFile[]): ScanResult {
  const { dir, scanPath } = stageForScan(root, files);
  const output = join(dir, "report");
  try {
    execFileSync(
      join(root, "node_modules", ".bin", "jscpd"),
      [
        ...scanPath.keys(),
        "--format",
        [...new Set(files.map((file) => file.format))].sort().join(","),
        "--min-tokens",
        String(MIN_TOKENS),
        "--min-lines",
        String(MIN_LINES),
        "--max-lines",
        String(MAX_LINES),
        "--max-size",
        MAX_SIZE,
        // One authority for scope, and it is the file list above. jscpd reads `.gitignore` by
        // default and would otherwise apply it a second time to a list `git ls-files
        // --exclude-standard` has already filtered — which is how the scan copies, staged into an
        // ignored directory, silently stopped being read. Nothing ignored can reach this list.
        "--no-gitignore",
        "--reporters",
        "json",
        "--output",
        output,
        "--silent",
      ],
      { cwd: root, encoding: "utf8", stdio: ["ignore", "ignore", "pipe"], maxBuffer: 32 * 1024 * 1024 },
    );

    const report = JSON.parse(readFileSync(join(output, "jscpd-report.json"), "utf8")) as JscpdReport;

    const analyzed = new Set<string>();
    for (const { sources } of Object.values(report.statistics.formats)) {
      for (const name of Object.keys(sources)) {
        const real = scanPath.get(resolve(root, name));
        if (real !== undefined) analyzed.add(real);
      }
    }

    const duplicates = report.duplicates.map((duplicate) => {
      const where = [duplicate.firstFile, duplicate.secondFile]
        .map((file) => `${scanPath.get(resolve(root, file.name)) ?? file.name}:${file.start}`)
        .sort();
      return {
        hash: fingerprint(duplicate.format, duplicate.fragment),
        format: duplicate.format,
        lines: duplicate.lines,
        tokens: duplicate.tokens,
        where,
      };
    });

    return { duplicates, analyzed };
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

function readBaseline(root: string): BaselineEntry[] {
  const path = join(root, BASELINE_RELATIVE_PATH);
  if (!existsSync(path)) return [];
  return JSON.parse(readFileSync(path, "utf8")) as BaselineEntry[];
}

function writeBaseline(root: string, entries: BaselineEntry[]): void {
  const sorted = [...entries].sort((a, b) => a.hash.localeCompare(b.hash));
  writeFileSync(join(root, BASELINE_RELATIVE_PATH), `${JSON.stringify(sorted, null, 2)}\n`);
}

/** `format a, format b` — the per-language file counts the banner carries alongside the total. */
function formatBreakdown(files: ScopedFile[]): string {
  const counts = new Map<string, number>();
  for (const file of files) counts.set(file.format, (counts.get(file.format) ?? 0) + 1);
  return [...counts]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([format, count]) => `${format} ${count}`)
    .join(", ");
}

function describe(entry: Duplicate): string {
  return `  ${entry.format}, ${entry.lines} lines / ${entry.tokens} tokens [${entry.hash}]\n    ${entry.where.join("\n    ")}`;
}

/**
 * Exit codes are the gauntlet's three (`bin/gauntlet`:20-23): 0 clean, 1 a real finding, 2 the gate
 * could not run. A bucket nothing declares is a 2 — the gate did not measure anything, and
 * reporting that as a finding would put it in the same bin as duplication somebody has to remove.
 */
export function runCloneGate(root: string, argv: readonly string[]): number {
  const venue = process.env.GAUNTLET_VENUE;
  if (venue !== undefined && venue !== "") {
    // Rule 6. `bin/gauntlet stop` runs the `test` slot, and the `test` slot runs this — so without
    // this line, turning the gate on would put a two-second scan at the end of every turn. The
    // gauntlet is not this gate's scheduler at any venue: `npm run check` and CI each run it once.
    console.error(
      `clone gate: not run inside \`bin/gauntlet ${venue}\` — it runs in \`npm run check\` and in CI (docs/agents/clone-gate.md, rule 6)`,
    );
    return 0;
  }

  const { files, undeclared, nested } = scopeOf(root);
  if (nested.length > 0) {
    // Rule 3 permits the skip and forbids doing it quietly. Printed before the refusal check as
    // well as before the banner, so the line is there whichever way the run ends.
    console.log(
      `clone gate: skipped ${nested.length} nested git ${nested.length === 1 ? "repository" : "repositories"} — ${nested.join(", ")}` +
        " — each is another repo's checkout, and its files are that repo's to scan, not this one's.",
    );
  }
  if (undeclared.size > 0) {
    console.error(refusal(undeclared));
    return 2;
  }

  const { duplicates, analyzed } = scan(root, files);

  // A file shorter than the minimum clone cannot hold one, and jscpd leaves it out of the report
  // rather than reporting it as read. That is arithmetic, not a coverage hole — but it is counted
  // in the banner, because the difference between "nothing to match" and "never looked" is the
  // only thing a reader of a green run has to go on.
  const missing = files.filter((file) => !analyzed.has(file.path));
  const tooShort = missing.filter((file) => lineCount(join(root, file.path)) < MIN_LINES);
  const unread = missing.filter((file) => !tooShort.includes(file)).map((file) => file.path);

  const shortNote = tooShort.length > 0 ? ` (${tooShort.length} under the ${MIN_LINES}-line minimum, nothing to match)` : "";
  console.log(`clone gate: scanned ${files.length} files${shortNote} — ${formatBreakdown(files)}`);

  if (unread.length > 0) {
    // The other half of rule 3: a file that was in scope and that jscpd did not report reading is a
    // hole, whatever the reason (its maxSize default, an extension its tokeniser declined). A
    // number that silently stopped covering a file is the failure this whole runner exists for.
    console.error(
      `clone gate: ${unread.length} in-scope file(s) were handed to jscpd and not read back:\n  ${unread.join("\n  ")}\n` +
        "Exclude them by path with a reason, or find out why the scan dropped them. Do not leave this unresolved.",
    );
    return 2;
  }

  const baseline = readBaseline(root);
  const baselineHashes = new Set(baseline.map((entry) => entry.hash));
  const foundHashes = new Set(duplicates.map((entry) => entry.hash));

  if (argv.includes("--seed-baseline")) {
    // Write-once, by refusal. Rule 5 lets a repo carry the debt it already had; it does not let a
    // later run absorb new debt by re-recording whatever is there now, which is what an
    // `--update` that overwrote would quietly become.
    if (baseline.length > 0) {
      console.error(
        `clone gate: ${BASELINE_RELATIVE_PATH} already exists with ${baseline.length} entries. The baseline only shrinks — fix the clone or run --prune-baseline; there is no way to add to it.`,
      );
      return 2;
    }
    const seeded = [...new Map(duplicates.map((entry) => [entry.hash, entry])).values()];
    writeBaseline(root, seeded);
    console.log(`clone gate: recorded ${seeded.length} baseline entries in ${BASELINE_RELATIVE_PATH}`);
    return 0;
  }

  if (argv.includes("--prune-baseline")) {
    const kept = baseline.filter((entry) => foundHashes.has(entry.hash));
    writeBaseline(root, kept);
    console.log(
      `clone gate: pruned ${baseline.length - kept.length} entries that no longer reproduce; ${kept.length} left`,
    );
    return 0;
  }

  const introduced = [...new Map(duplicates.filter((entry) => !baselineHashes.has(entry.hash)).map((entry) => [entry.hash, entry])).values()];
  const stale = baseline.filter((entry) => !foundHashes.has(entry.hash));

  if (introduced.length > 0) {
    console.error(`clone gate: ${introduced.length} clone(s) not in the baseline:\n${introduced.map(describe).join("\n")}`);
  }
  if (stale.length > 0) {
    // Rule 5's ratchet, and the reason it is a finding rather than a courtesy: an entry that stops
    // reproducing has been *paid off*, and leaving it in the file keeps the room for it open.
    console.error(
      `clone gate: ${stale.length} baseline entr(ies) no longer reproduce. The baseline only shrinks — delete them:\n` +
        `${stale.map(describe).join("\n")}\n  bin/clone-gate --prune-baseline`,
    );
  }
  if (introduced.length > 0 || stale.length > 0) return 1;

  console.log(`clone gate: ${duplicates.length} clone(s), all carried by ${BASELINE_RELATIVE_PATH} (${baseline.length} entries)`);
  return 0;
}

// --- CLI -------------------------------------------------------------------------------------
//
// `bin/clone-gate`                    scan; red on a clone the baseline does not carry.
// `bin/clone-gate --seed-baseline`    write the baseline once, at turn-on. Refuses if one exists.
// `bin/clone-gate --prune-baseline`   drop entries that no longer reproduce. Only ever shrinks.
//
// `pathToFileURL(process.argv[1])` rather than a hand-built `file://` — this repo's own checkout
// path has a space in it, and the naive form loses the percent-encoding.
const isMain = process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href;

if (isMain) {
  const args = process.argv.slice(2);
  const root = args.find((arg) => !arg.startsWith("--")) ?? process.cwd();
  process.exit(runCloneGate(resolve(root), args));
}
