import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { copyFileSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { weak } from "@jscpd/core";
import { FORMATS, tokenize } from "@jscpd/tokenizer";
import { childEnv } from "./child-env.ts";

/**
 * The clone gate (`docs/agents/clone-gate.md`), jscpd behind a runner that owns the four rules
 * jscpd itself has no opinion about.
 *
 * The detector is the easy half. What makes a gate worth having is that **a passing run cannot
 * mean "I read nothing"** — so this file re-derives its own scope on every run rather than
 * trusting a list somebody wrote once:
 *
 * - the file set is `git ls-files` from the root, so a new directory is in scope the moment it
 *   exists (rule 1) — the failure the doc records is a hand-kept root list that never gained
 *   `bin/`;
 * - the `--format` list is derived from the extensions actually present, looked up in jscpd's own
 *   `FORMATS` table, never typed here (rule 2);
 * - every file that survives the path rules is bucketed before the scan, and an undeclared bucket
 *   **refuses the run** rather than being skipped (rule 3), as does any file jscpd silently
 *   declined to read — its `maxSize` default is exactly the kind of quiet hole this catches;
 * - the banner prints how many files were actually scanned (rule 4).
 *
 * Rule 5 is `clone-gate.baseline.json`: written once, at turn-on, over the 98 clones this repo
 * already had, and it only ever shrinks — a clone that stops reproducing is a finding here until
 * its baseline entry is deleted. Its one door is `recut`, for the entry whose fingerprint moved
 * without the duplication moving (#282, ADR-0116); a carry substitutes one entry for one and the
 * count never rises.
 *
 * Rule 6 is where it runs: the `test` and `all` slots of `.claude/contract.json` and CI, never the
 * `stop` slot. This repo's `stop` slot is `bin/gauntlet stop`, which runs the `test` slot — so the
 * gauntlet exports `GAUNTLET_VENUE` and this file declines when it sees it. The gauntlet does not
 * schedule the clone gate at any venue; `npm run check` and `.github/workflows/verify.yml` do,
 * exactly once each.
 */

/** Where the ratchet lives, relative to the repo root. */
export const BASELINE_RELATIVE_PATH = ".Workflow/agent-workflows/shared/clone-gate.baseline.json";

/**
 * jscpd's own defaults for what counts as a clone, restated here so the numbers are decisions this
 * repo made rather than ones it inherited and would never notice changing.
 */
const MIN_TOKENS = 50;
const MIN_LINES = 5;

/**
 * jscpd's two size heuristics, both raised past anything this repo holds. Their defaults — 1000
 * lines and 100kb — drop a file from the scan *and from the report*, which is the exact shape rule
 * 3 exists to catch: turning the gate on here, `session-capture.test.ts` (1035 lines) vanished from
 * a green run. Raised rather than removed because a genuinely enormous file is worth an explicit
 * exclusion, not a silent one.
 */
const MAX_LINES = 100_000;
const MAX_SIZE = "8mb";

/**
 * Where a file whose language its name does not carry is copied for the scan. Inside the repo, not
 * `os.tmpdir()`: jscpd resolves its inputs against the working directory and silently drops a path
 * outside it. Each run stages into its own child of this directory (`stageForScan`) and deletes
 * only that child; the parent is excluded from scope, gitignored, and listed in `eslint.config.js`'s
 * ignores, so a killed run's leftovers never enter the next one and no concurrent walker ever
 * descends into a tree mid-deletion.
 */
const SCAN_DIR = ".clone-gate-scan";

/**
 * Paths left out of the scan. Rule 1 allows an exclusion and requires the reason to sit next to
 * the pattern — not in a commit message, not in someone's memory. A path matches when it is the
 * entry itself or lives under it.
 */
const EXCLUDED_PATHS: ReadonlyArray<{ path: string; why: string }> = [
  {
    path: "package-lock.json",
    why: "npm's generated lockfile. Its repetition is the format's, not this repo's — nobody refactors it, and a finding there could only ever be noise.",
  },
  {
    path: ".Workflow/agent-workflows/watchdog/adr-corpus.evidence.json",
    why: "generated by `generate-corpus-fixture.ts` from docs/adr and docs/research, and gated by its own `regenerate && diff` in `bin/gauntlet push`. Duplication in it is duplication in the sources it was generated from, counted twice.",
  },
  {
    path: BASELINE_RELATIVE_PATH,
    why: "this gate's own output. Its entries are structurally alike by construction, so scanning it would eventually have the gate reporting itself.",
  },
  {
    path: SCAN_DIR,
    why: "this gate's own scratch copies (see `stageForScan`). Deleted after every run; excluded so a killed run's leftovers can never be scanned as if they were source.",
  },
];

/**
 * Extensions present in the tree that the gate does not read, each with the reason. Rule 2: leaving
 * code out of scope is allowed; doing it silently is not. Anything present and named by neither
 * this list nor a jscpd format refuses the run.
 */
const IGNORED_EXTENSIONS: ReadonlyArray<{ ext: string; why: string }> = [
  {
    ext: "gitignore",
    why: "a list of path patterns. It has no lexical structure to tokenise, and the only 'duplication' it can hold is two patterns spelled alike, which is not a refactor.",
  },
  {
    ext: "txt",
    why: "plain prose fixtures. jscpd ships a `txt` format but tokenises nothing from them, so declaring the extension is the honest form of what the scan would do anyway.",
  },
];

/**
 * Files whose language nothing inside them states. Rule 2 is satisfied by declaring the language,
 * not only by declining to read it — a file this repo can run belongs in the scan, and dropping it
 * because its name is uninformative is how `bin/` went uncovered in the failure the doc records.
 */
const PATH_FORMATS: ReadonlyArray<{ path: string; format: string; why: string }> = [
  {
    path: ".husky/pre-push",
    format: "bash",
    why: "husky v9 sources its hooks rather than executing them, so they carry neither a shebang nor an extension. git runs this as a shell script; nothing in the file says so.",
  },
];

/**
 * Interpreters a shebang can name, and the jscpd format that reads that language. This is what
 * keeps `bin/gauntlet`, `bin/new-adr` and `bin/close-ticket` in scope: jscpd resolves a format from
 * the file extension alone, and every one of those files has none. They are copied under a
 * synthetic extension for the scan (see `stageForScan`) and reported under their real path.
 */
const SHEBANG_FORMATS: Readonly<Record<string, string>> = {
  bash: "bash",
  sh: "bash",
  zsh: "bash",
  python: "python",
  python3: "python",
  node: "javascript",
};

/** One file the gate will scan, and how it resolved that file's language. */
interface ScopedFile {
  /** Repo-relative path, as `git ls-files` and every report line spell it. */
  path: string;
  /** The jscpd format that reads it. */
  format: string;
  /** The extension jscpd needs to see to pick that format — supplied by us for a shebang file. */
  ext: string;
  /** True when the format came from a shebang rather than the file's own extension. */
  staged: boolean;
}

/** Extension → jscpd format, inverted from jscpd's own table so it cannot go stale against it. */
function extensionFormats(): Map<string, string> {
  const byExt = new Map<string, string>();
  for (const [format, { exts }] of Object.entries(FORMATS)) {
    for (const ext of exts) if (!byExt.has(ext)) byExt.set(ext, format);
  }
  return byExt;
}

/** A path's extension, lowercased, or `""` for a file whose name carries none. */
function extensionOf(path: string): string {
  const name = path.slice(path.lastIndexOf("/") + 1);
  const dot = name.lastIndexOf(".");
  // A leading dot is a name, not an extension: `.gitignore` is `gitignore`, `.env.example` is
  // `example`. Anything else with no dot at all buckets as `""`, the shebang case.
  return dot > 0 ? name.slice(dot + 1).toLowerCase() : name.startsWith(".") ? name.slice(1).toLowerCase() : "";
}

/** How many lines a file holds — asked only about the files jscpd left out of its report. */
function lineCount(absolutePath: string): number {
  try {
    return readFileSync(absolutePath, "utf8").split("\n").length;
  } catch {
    return 0;
  }
}

/**
 * Splits every in-scope file jscpd did not report reading into the two shapes rule 3 tells apart:
 * `tooShort` is arithmetic (nothing under `MIN_LINES` could hold a clone), `unread` is the hole rule
 * 3 exists to catch. Shared by `runCloneGate`'s own scan and `repairAcceptanceBaseline`'s, which
 * would otherwise restate this identically — the fix for the clone `bin/clone-gate` found in this
 * file itself once `repairAcceptanceBaseline` first landed.
 */
function unreadFiles(
  root: string,
  files: ScopedFile[],
  analyzed: Set<string>,
): { tooShort: ScopedFile[]; unread: string[] } {
  const missing = files.filter((file) => !analyzed.has(file.path));
  const tooShort = missing.filter((file) => lineCount(join(root, file.path)) < MIN_LINES);
  const unread = missing.filter((file) => !tooShort.includes(file)).map((file) => file.path);
  return { tooShort, unread };
}

/** `unreadFiles`' message, in the one shape both its callers report it in — a refusal, never a partial run. */
function unreadRefusal(unread: string[]): string {
  return (
    `clone gate: ${unread.length} in-scope file(s) were handed to jscpd and not read back:\n  ${unread.join("\n  ")}\n` +
    "Exclude them by path with a reason, or find out why the scan dropped them."
  );
}

/** The paths a clone names, without the line numbers that move under any edit above them. */
function filesOf(where: readonly string[]): string {
  return [...where].map((location) => location.slice(0, location.lastIndexOf(":"))).sort().join("\0");
}

/** How many lines a fragment spans — read off the fragment rather than trusted from the entry. */
function fragmentLines(fragment: string): number {
  return fragment.split("\n").length;
}

/**
 * A fragment reduced to the code in it: jscpd's own tokens, filtered by jscpd's own `weak` handler,
 * which is the one of its three that drops comments as well as blank lines and line breaks.
 *
 * Imported rather than restated for the reason the `format` list is derived from `FORMATS` rather
 * than typed — a rule about a tokeniser, written down twice, is a rule that is right the day it is
 * written. A format `tokenize` cannot read falls back to the raw text, which is the answer this
 * comparison had before it existed.
 */
function signature(format: string, fragment: string): string[] {
  try {
    return tokenize(fragment, format)
      .filter((token) => weak(token))
      .map((token) => `${token.type} ${token.value}`);
  } catch {
    return [fragment];
  }
}

/** True when `needle` appears in `haystack` unbroken — token identity, never string containment. */
function containsRun(haystack: string[], needle: string[]): boolean {
  if (needle.length === 0 || needle.length > haystack.length) return false;
  for (let start = 0; start <= haystack.length - needle.length; start++) {
    let matched = true;
    for (let offset = 0; matched && offset < needle.length; offset++) {
      matched = haystack[start + offset] === needle[offset];
    }
    if (matched) return true;
  }
  return false;
}

/**
 * True when `found` is `entry`'s own clone, re-cut — the same duplication, reported over a different
 * span of text, and therefore under a different `hash`.
 *
 * This is the door #282 found missing. A fingerprint is the reported fragment's text, which is not
 * the same thing as the clone: jscpd's fragment is a slice of the source between two matched tokens,
 * and it carries whatever sits inside that slice — including comments, which the detector's default
 * mode does not require to match. So **rewording a comment inside a baselined clone changes its
 * fingerprint while changing nothing about the duplication**. That is what #274 hit: `fakeGh` in
 * `fixer.test.ts` and `open-questions.test.ts`, 13 lines and 107 tokens before and after, in the same
 * two files at the same two lines, under a new hash. The old entry stopped reproducing (a finding),
 * the new one was not in the baseline (a finding), and `--prune-baseline` only ever deleted — so a
 * clone the repo had agreed to tolerate became an unlandable tree, escapable only by refactoring in
 * the middle of an unrelated change. The same happens when the *extent* moves, which it does when
 * content beside the clone becomes shared and the matched run grows through it.
 *
 * A carry is a substitution, never a growth (`--prune-baseline` still has no way to *add* an entry),
 * and the three conditions are what keep it from being one:
 *
 * - **the same files**, so a baselined clone's identity can never migrate onto duplication
 *   somewhere else — this is what fences the looseness of `signature` to the one pair of files the
 *   baseline already named;
 * - **one signature inside the other**, so the new entry is the old debt's own code with its edges
 *   redrawn or its commentary rewritten, not a different clone that happens to share a file pair;
 * - **grown by less than a clone**, in lines read off the fragments. The gate reports nothing under
 *   `MIN_LINES`, so an edge smaller than that is an edge it has no opinion about, and refusing it
 *   would be refusing something this gate cannot measure. Anything bigger is new duplication and
 *   stays a finding.
 *
 * Nothing here reads `lines`, `tokens` or the entry's own line numbers. Every input is either the
 * fragment — which `hash` is over, so `baselineDiff` can re-derive it and a hand-edited one cannot
 * lie — or the paths. That is what keeps the new field from widening what a baseline file can claim.
 */
function recut(entry: BaselineEntry, found: Duplicate): boolean {
  if (entry.fragment === undefined || entry.format !== found.format) return false;
  if (filesOf(entry.where) !== filesOf(found.where)) return false;
  const was = signature(entry.format, entry.fragment);
  const now = signature(found.format, found.fragment);
  if (!containsRun(now, was) && !containsRun(was, now)) return false;
  return fragmentLines(found.fragment) - fragmentLines(entry.fragment) < MIN_LINES;
}

/** A baseline entry and the re-cut of it this scan found, the pair `--prune-baseline` substitutes. */
interface Carry {
  from: BaselineEntry;
  to: Duplicate;
}

/**
 * Pairs each stale entry with its re-cut, at most one apiece and each found clone claimed once.
 * Deterministic — stale entries in hash order, and the smallest re-cut wins — because two runs over
 * the same tree that carried different entries would be a ratchet nobody could review.
 */
function carriesOf(stale: BaselineEntry[], introduced: Duplicate[]): Carry[] {
  const claimed = new Set<string>();
  const carries: Carry[] = [];
  for (const entry of [...stale].sort((a, b) => a.hash.localeCompare(b.hash))) {
    const candidate = introduced
      .filter((found) => !claimed.has(found.hash) && recut(entry, found))
      .sort((a, b) => fragmentLines(a.fragment) - fragmentLines(b.fragment) || a.hash.localeCompare(b.hash))[0];
    if (candidate === undefined) continue;
    claimed.add(candidate.hash);
    carries.push({ from: entry, to: candidate });
  }
  return carries;
}

/**
 * The baseline read against one scan's duplicates, and the three diffs every caller of the baseline
 * needs from that pairing: `introduced` (a clone the baseline does not carry), `stale` (a baseline
 * entry that no longer reproduces), and `carried` (a stale entry and the introduced clone that is
 * the same debt re-cut — see `recut`). A carry is in neither of the other two lists: it is not new
 * duplication and it is not paid-off debt. `runCloneGate`'s own report and
 * `repairAcceptanceBaseline` both start from exactly this split.
 *
 * `corrupt` is a baseline entry carrying a `fragment` that does not hash to its own `hash`. Only a
 * hand edit can produce one, and it is a refusal rather than a skip for the reason rule 3 gives
 * about every other hole: a fingerprint nobody re-derives is a fingerprint that stops meaning
 * anything, quietly.
 */
function baselineDiff(
  root: string,
  duplicates: Duplicate[],
): {
  baseline: BaselineEntry[];
  introduced: Duplicate[];
  stale: BaselineEntry[];
  carried: Carry[];
  corrupt: BaselineEntry[];
} {
  const baseline = readBaseline(root);
  const corrupt = baseline.filter(
    (entry) => entry.fragment !== undefined && fingerprint(entry.format, entry.fragment) !== entry.hash,
  );
  const baselineHashes = new Set(baseline.map((entry) => entry.hash));
  const foundHashes = new Set(duplicates.map((entry) => entry.hash));
  const unbaselined = [
    ...new Map(duplicates.filter((entry) => !baselineHashes.has(entry.hash)).map((entry) => [entry.hash, entry])).values(),
  ];
  const unreproduced = baseline.filter((entry) => !foundHashes.has(entry.hash));
  const carried = corrupt.length > 0 ? [] : carriesOf(unreproduced, unbaselined);
  const carriedFrom = new Set(carried.map((carry) => carry.from.hash));
  const carriedTo = new Set(carried.map((carry) => carry.to.hash));
  return {
    baseline,
    introduced: unbaselined.filter((entry) => !carriedTo.has(entry.hash)),
    stale: unreproduced.filter((entry) => !carriedFrom.has(entry.hash)),
    carried,
    corrupt,
  };
}

/** The interpreter a `#!` line names, by basename, or `undefined` when there is no shebang. */
function shebangInterpreter(absolutePath: string): string | undefined {
  let head: string;
  try {
    head = readFileSync(absolutePath, "utf8").slice(0, 200).split("\n", 1)[0] ?? "";
  } catch {
    return undefined;
  }
  if (!head.startsWith("#!")) return undefined;
  const words = head.slice(2).trim().split(/\s+/);
  // `#!/usr/bin/env bash` names the interpreter in the second word; `#!/bin/bash` in the first.
  const named = words[0]?.endsWith("/env") ? words[1] : words[0];
  return named?.slice(named.lastIndexOf("/") + 1);
}

/**
 * Every file the repo tracks or has newly written, from the root. `--others --exclude-standard`
 * is what puts a file that is not committed yet in scope: new code is exactly when a clone is
 * cheapest to not write.
 *
 * `childEnv()` because `GIT_DIR` beats a cwd, and this runs downstream of hooks that export it.
 */
function repoFiles(root: string): string[] {
  const out = execFileSync("git", ["ls-files", "-z", "--cached", "--others", "--exclude-standard"], {
    cwd: root,
    env: childEnv(),
    encoding: "utf8",
    maxBuffer: 32 * 1024 * 1024,
  });
  return out.split("\0").filter((path) => path.length > 0);
}

/**
 * True for the one entry shape `git ls-files` uses that is not a file: a **nested git repository**,
 * reported as its directory with a trailing slash — `knowledge-base/` — because everything inside
 * it belongs to *that* repository's index, not this one's. CI checks the private corpus repo out
 * there (`audit.yml`), so the entry exists on the runner and nowhere else, which is how every local
 * gauntlet stayed green while the Audit lane's `pre-push` died on a refusal (#218).
 *
 * It is not enough to trust the slash. A directory that is not a repository would be a real gap in
 * scope, and letting it through on punctuation alone is exactly the silent skip rule 3 forbids — so
 * the entry has to actually carry a `.git`, and anything else with a trailing slash still lands in
 * `undeclared` and still refuses the run.
 */
function isNestedRepository(root: string, path: string): boolean {
  return path.endsWith("/") && existsSync(join(root, path, ".git"));
}

/** What bucketing the tree produced: what will be scanned, and what nothing accounts for. */
interface Scope {
  files: ScopedFile[];
  /** Extension → the files nothing declares. The refusal in rule 3 is built from this. */
  undeclared: Map<string, string[]>;
  /**
   * Nested repositories skipped, in `git ls-files` spelling. Named in the banner rather than
   * dropped: rule 3's whole point is that a skip nobody can see reads the same as a clean scan.
   */
  nested: string[];
  /**
   * Index entries with no file on disk — a `git rm`'d path, or one deleted in the worktree and not
   * staged yet. `git ls-files --cached` reports them because they are still in the index, and
   * handing one to jscpd killed the whole run with an empty exit 1: no message, no report, no way
   * to tell it from a real refusal. A run that deleted a module then lost its push to that is how
   * #263's implementer lost 31 minutes of work.
   *
   * Skipped, because a file that is not on disk is not part of the tree being scanned — and named,
   * because rule 3's whole point is that a skip nobody can see reads the same as a clean one.
   */
  deleted: string[];
}

/**
 * Buckets every file under `root` into scanned, excluded, ignored, or undeclared. This is the
 * self-audit half of rule 3, and it runs *before* the scan so a repo that grew a language gets a
 * refusal rather than a number that quietly stopped covering it.
 */
export function scopeOf(root: string): Scope {
  const byExt = extensionFormats();
  const ignored = new Set(IGNORED_EXTENSIONS.map((entry) => entry.ext));
  const files: ScopedFile[] = [];
  const undeclared = new Map<string, string[]>();
  const nested: string[] = [];
  const deleted: string[] = [];

  for (const path of repoFiles(root)) {
    if (EXCLUDED_PATHS.some((entry) => path === entry.path || path.startsWith(`${entry.path}/`))) continue;
    if (isNestedRepository(root, path)) {
      nested.push(path);
      continue;
    }
    // Checked before the extension rules, so a deleted file is never bucketed as undeclared and
    // never reaches the scan — the two ways an absent path turns into a message about the wrong
    // thing.
    if (!existsSync(join(root, path))) {
      deleted.push(path);
      continue;
    }
    const ext = extensionOf(path);
    const byExtension = byExt.get(ext);
    if (byExtension && !ignored.has(ext)) {
      files.push({ path, format: byExtension, ext, staged: false });
      continue;
    }
    if (ignored.has(ext)) continue;
    const interpreter = shebangInterpreter(join(root, path));
    const declared = PATH_FORMATS.find((entry) => entry.path === path)?.format;
    const byShebang = declared ?? (interpreter === undefined ? undefined : SHEBANG_FORMATS[interpreter]);
    if (byShebang) {
      files.push({ path, format: byShebang, ext: FORMATS[byShebang]?.exts[0] ?? ext, staged: true });
      continue;
    }
    const bucket = undeclared.get(ext) ?? [];
    bucket.push(path);
    undeclared.set(ext, bucket);
  }

  files.sort((a, b) => a.path.localeCompare(b.path));
  nested.sort((a, b) => a.localeCompare(b));
  deleted.sort((a, b) => a.localeCompare(b));
  return { files, undeclared, nested, deleted };
}

/**
 * Rule 3's message. It names each undeclared bucket, its file count, an example path, and *both*
 * ways to resolve it — because the failure mode this replaces is someone reaching for whichever
 * one the error happened to mention.
 */
function refusal(undeclared: Map<string, string[]>): string {
  const lines = [
    "clone gate: refusing to scan — these files are covered by neither a format nor an ignore rule.",
    "A bucket nothing declares is a bucket the gate would have skipped silently, and a silent skip",
    "is indistinguishable from a clean scan (docs/agents/clone-gate.md, rule 3).",
    "",
  ];
  for (const [ext, paths] of [...undeclared].sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(`  .${ext || "(no extension)"} — ${paths.length} file(s), e.g. ${paths[0]}`);
  }
  lines.push(
    "",
    "Resolve each bucket one of two ways, in .Workflow/agent-workflows/shared/clone-gate.ts:",
    "  - scan it: give the language a jscpd format (or a SHEBANG_FORMATS entry, for a file whose",
    "    language its name does not carry);",
    "  - or don't: add the extension to IGNORED_EXTENSIONS with the reason it is out of scope.",
  );
  return lines.join("\n");
}

/**
 * jscpd picks a file's language from its extension and has no per-file override, so a shebang
 * script with no extension is unreadable to it. Those files are copied into a scratch tree under
 * the extension their language uses, and the copy's path maps back to the real one for every
 * report line. Returns the scratch directory (to delete) and that mapping.
 */
function stageForScan(root: string, files: ScopedFile[]): { dir: string; scanPath: Map<string, string> } {
  // One child per run under a fixed, ignored parent — never the parent itself. Two gates run at
  // once on a push (`bin/gauntlet push`'s `clones` check beside the `test` slot's `clone:check`),
  // and `.claude/hooks/gauntlet.test.ts` drives a whole-repo eslint in between: a shared directory
  // one run deletes while another scans it is a wrong answer, and a directory that vanishes under
  // eslint's walker is `ENOENT: scandir .clone-gate-scan` (Integrate run 33325994300). The parent
  // stays put and every walker is told to skip it; only the child is created and removed here.
  const parent = join(root, SCAN_DIR);
  mkdirSync(parent, { recursive: true });
  const dir = mkdtempSync(join(parent, "run-"));
  const scanPath = new Map<string, string>();
  for (const file of files) {
    if (!file.staged) {
      scanPath.set(resolve(root, file.path), file.path);
      continue;
    }
    const staged = join(dir, `${file.path.replace(/\//g, "__")}.${file.ext}`);
    copyFileSync(join(root, file.path), staged);
    scanPath.set(resolve(staged), file.path);
  }
  return { dir, scanPath };
}

/** One duplicated fragment jscpd found, in the two shapes this file needs it in. */
interface Duplicate {
  /** Stable across line movement and file renames: the fragment's own content, plus its language. */
  hash: string;
  format: string;
  lines: number;
  tokens: number;
  /**
   * Repo-relative, for a human reading the failure. Never part of `hash`, and never refreshed once
   * written — the line numbers are where the clone was when the entry was recorded, and rewriting
   * them on every prune would put this file in the diff of every change that moves a line above one.
   */
  where: string[];
  /** The duplicated text itself. What `hash` is over, and the only thing a re-cut is recognisable by. */
  fragment: string;
}

/**
 * One baseline entry — a `Duplicate` minus nothing, so a stale entry is readable on its own.
 *
 * `fragment` is optional for one reason: a baseline written before the field existed. Such an entry
 * still matches by `hash` exactly as it always did; it simply cannot be carried across a re-cut
 * (`recut`), and `--prune-baseline` fills the fragment in the first time it sees the clone reproduce.
 */
type BaselineEntry = Omit<Duplicate, "fragment"> & { fragment?: string };

interface JscpdReport {
  statistics: { formats: Record<string, { sources: Record<string, unknown> }> };
  duplicates: Array<{
    format: string;
    fragment: string;
    lines: number;
    tokens: number;
    firstFile: { name: string; start: number };
    secondFile: { name: string; start: number };
  }>;
}

/** What one scan measured: the clones, and every file jscpd confirmed it actually read. */
interface ScanResult {
  duplicates: Duplicate[];
  analyzed: Set<string>;
}

function fingerprint(format: string, fragment: string): string {
  return createHash("sha256").update(`${format}\0${fragment}`).digest("hex").slice(0, 16);
}

/** Runs jscpd over exactly the scoped files and reads its JSON report back. */
function scan(root: string, files: ScopedFile[]): ScanResult {
  const { dir, scanPath } = stageForScan(root, files);
  const output = join(dir, "report");
  try {
    execFileSync(
      join(root, "node_modules", ".bin", "jscpd"),
      [
        ...scanPath.keys(),
        "--format",
        [...new Set(files.map((file) => file.format))].sort().join(","),
        "--min-tokens",
        String(MIN_TOKENS),
        "--min-lines",
        String(MIN_LINES),
        "--max-lines",
        String(MAX_LINES),
        "--max-size",
        MAX_SIZE,
        // One authority for scope, and it is the file list above. jscpd reads `.gitignore` by
        // default and would otherwise apply it a second time to a list `git ls-files
        // --exclude-standard` has already filtered — which is how the scan copies, staged into an
        // ignored directory, silently stopped being read. Nothing ignored can reach this list.
        "--no-gitignore",
        "--reporters",
        "json",
        "--output",
        output,
        "--silent",
      ],
      { cwd: root, encoding: "utf8", stdio: ["ignore", "ignore", "pipe"], maxBuffer: 32 * 1024 * 1024 },
    );

    const report = JSON.parse(readFileSync(join(output, "jscpd-report.json"), "utf8")) as JscpdReport;

    const analyzed = new Set<string>();
    for (const { sources } of Object.values(report.statistics.formats)) {
      for (const name of Object.keys(sources)) {
        const real = scanPath.get(resolve(root, name));
        if (real !== undefined) analyzed.add(real);
      }
    }

    const duplicates = report.duplicates.map((duplicate) => {
      const where = [duplicate.firstFile, duplicate.secondFile]
        .map((file) => `${scanPath.get(resolve(root, file.name)) ?? file.name}:${file.start}`)
        .sort();
      return {
        hash: fingerprint(duplicate.format, duplicate.fragment),
        format: duplicate.format,
        lines: duplicate.lines,
        tokens: duplicate.tokens,
        where,
        fragment: duplicate.fragment,
      };
    });

    return { duplicates, analyzed };
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

function readBaseline(root: string): BaselineEntry[] {
  const path = join(root, BASELINE_RELATIVE_PATH);
  if (!existsSync(path)) return [];
  return JSON.parse(readFileSync(path, "utf8")) as BaselineEntry[];
}

function writeBaseline(root: string, entries: BaselineEntry[]): void {
  const sorted = [...entries].sort((a, b) => a.hash.localeCompare(b.hash));
  const path = join(root, BASELINE_RELATIVE_PATH);
  // `mkdirSync` because `repairAcceptanceBaseline` can write the first baseline entry a scratch
  // fixture (or a checkout that never seeded one) has ever had — `--seed-baseline` never hits this
  // path in a real repo, where the directory already exists.
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, `${JSON.stringify(sorted, null, 2)}\n`);
}

/**
 * What `--prune-baseline` writes: the same entries minus the ones that no longer reproduce, with
 * each carried entry replaced by its re-cut. One entry out per entry in, never one more — which is
 * the property `regenerate-artifacts.ts` puts this file on its list for, and the one a carry must
 * not cost.
 *
 * Survivors are written back untouched but for one thing: an entry recorded before `fragment`
 * existed gets its fragment filled in from the scan that just matched it by hash. That is the whole
 * migration — no rewrite of `where`, `lines` or `tokens`, so the file lands in a diff once and then
 * stops moving under changes that only shift lines.
 */
function prunedBaseline(
  baseline: BaselineEntry[],
  duplicates: Duplicate[],
  stale: BaselineEntry[],
  carried: Carry[],
): BaselineEntry[] {
  const found = new Map(duplicates.map((entry) => [entry.hash, entry]));
  const carriedFrom = new Map(carried.map((carry) => [carry.from.hash, carry.to]));
  const gone = new Set(stale.map((entry) => entry.hash));
  const next: BaselineEntry[] = [];
  for (const entry of baseline) {
    if (gone.has(entry.hash)) continue;
    const replacement = carriedFrom.get(entry.hash);
    if (replacement !== undefined) {
      next.push(replacement);
      continue;
    }
    const fragment = entry.fragment ?? found.get(entry.hash)?.fragment;
    next.push(fragment === undefined ? entry : { ...entry, fragment });
  }
  return next;
}

/** `format a, format b` — the per-language file counts the banner carries alongside the total. */
function formatBreakdown(files: ScopedFile[]): string {
  const counts = new Map<string, number>();
  for (const file of files) counts.set(file.format, (counts.get(file.format) ?? 0) + 1);
  return [...counts]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([format, count]) => `${format} ${count}`)
    .join(", ");
}

function describe(entry: BaselineEntry): string {
  return `  ${entry.format}, ${entry.lines} lines / ${entry.tokens} tokens [${entry.hash}]\n    ${entry.where.join("\n    ")}`;
}

/** A carry, in the one shape both the finding and `--prune-baseline`'s receipt print it. */
function describeCarry(carry: Carry): string {
  return `${describe(carry.from)}\n  → re-cut as ${carry.to.lines} lines / ${carry.to.tokens} tokens [${carry.to.hash}]\n    ${carry.to.where.join("\n    ")}`;
}

/** `baselineDiff`'s `corrupt` message, in the one shape both its callers report it in. */
function corruptRefusal(corrupt: BaselineEntry[]): string {
  return (
    `clone gate: ${corrupt.length} baseline entr(ies) carry a fragment that does not hash to their own hash:\n` +
    `${corrupt.map(describe).join("\n")}\n` +
    `Only a hand edit can do that, and the fragment is what a re-cut is recognised by — restore ${BASELINE_RELATIVE_PATH} from git.`
  );
}

/**
 * Exit codes are the gauntlet's three (`bin/gauntlet`:20-23): 0 clean, 1 a real finding, 2 the gate
 * could not run. A bucket nothing declares is a 2 — the gate did not measure anything, and
 * reporting that as a finding would put it in the same bin as duplication somebody has to remove.
 */
export function runCloneGate(root: string, argv: readonly string[]): number {
  const venue = process.env.GAUNTLET_VENUE;
  if (venue !== undefined && venue !== "") {
    // Rule 6. `bin/gauntlet stop` runs the `test` slot, and the `test` slot runs this — so without
    // this line, turning the gate on would put a two-second scan at the end of every turn. The
    // gauntlet is not this gate's scheduler at any venue: `npm run check` and CI each run it once.
    console.error(
      `clone gate: not run inside \`bin/gauntlet ${venue}\` — it runs in \`npm run check\` and in CI (docs/agents/clone-gate.md, rule 6)`,
    );
    return 0;
  }

  const { files, undeclared, nested, deleted } = scopeOf(root);
  if (deleted.length > 0) {
    // Named for the same reason the nested skip is, and printed before the refusal check so the
    // line survives whichever way the run ends.
    console.log(
      `clone gate: skipped ${deleted.length} path${deleted.length === 1 ? "" : "s"} in the index with no file on disk — ${deleted.join(", ")}` +
        " — deleted but not staged, or staged and not yet committed; nothing to scan either way.",
    );
  }
  if (nested.length > 0) {
    // Rule 3 permits the skip and forbids doing it quietly. Printed before the refusal check as
    // well as before the banner, so the line is there whichever way the run ends.
    console.log(
      `clone gate: skipped ${nested.length} nested git ${nested.length === 1 ? "repository" : "repositories"} — ${nested.join(", ")}` +
        " — each is another repo's checkout, and its files are that repo's to scan, not this one's.",
    );
  }
  if (undeclared.size > 0) {
    console.error(refusal(undeclared));
    return 2;
  }

  const { duplicates, analyzed } = scan(root, files);

  // A file shorter than the minimum clone cannot hold one, and jscpd leaves it out of the report
  // rather than reporting it as read. That is arithmetic, not a coverage hole — but it is counted
  // in the banner, because the difference between "nothing to match" and "never looked" is the
  // only thing a reader of a green run has to go on.
  const { tooShort, unread } = unreadFiles(root, files, analyzed);

  const shortNote = tooShort.length > 0 ? ` (${tooShort.length} under the ${MIN_LINES}-line minimum, nothing to match)` : "";
  console.log(`clone gate: scanned ${files.length} files${shortNote} — ${formatBreakdown(files)}`);

  if (unread.length > 0) {
    // The other half of rule 3: a file that was in scope and that jscpd did not report reading is a
    // hole, whatever the reason (its maxSize default, an extension its tokeniser declined). A
    // number that silently stopped covering a file is the failure this whole runner exists for.
    console.error(`${unreadRefusal(unread)} Do not leave this unresolved.`);
    return 2;
  }

  const { baseline, introduced, stale, carried, corrupt } = baselineDiff(root, duplicates);

  if (corrupt.length > 0) {
    console.error(corruptRefusal(corrupt));
    return 2;
  }

  if (argv.includes("--seed-baseline")) {
    // Write-once, by refusal. Rule 5 lets a repo carry the debt it already had; it does not let a
    // later run absorb new debt by re-recording whatever is there now, which is what an
    // `--update` that overwrote would quietly become.
    if (baseline.length > 0) {
      console.error(
        `clone gate: ${BASELINE_RELATIVE_PATH} already exists with ${baseline.length} entries. The baseline only shrinks — fix the clone or run --prune-baseline; there is no way to add to it.`,
      );
      return 2;
    }
    const seeded = [...new Map(duplicates.map((entry) => [entry.hash, entry])).values()];
    writeBaseline(root, seeded);
    console.log(`clone gate: recorded ${seeded.length} baseline entries in ${BASELINE_RELATIVE_PATH}`);
    return 0;
  }

  if (argv.includes("--prune-baseline")) {
    writeBaseline(root, prunedBaseline(baseline, duplicates, stale, carried));
    const left = baseline.length - stale.length;
    console.log(
      `clone gate: pruned ${stale.length} entries that no longer reproduce, carried ${carried.length} across a re-cut; ${left} left`,
    );
    return 0;
  }

  if (introduced.length > 0) {
    console.error(`clone gate: ${introduced.length} clone(s) not in the baseline:\n${introduced.map(describe).join("\n")}`);
  }
  if (stale.length > 0) {
    // Rule 5's ratchet, and the reason it is a finding rather than a courtesy: an entry that stops
    // reproducing has been *paid off*, and leaving it in the file keeps the room for it open.
    console.error(
      `clone gate: ${stale.length} baseline entr(ies) no longer reproduce. The baseline only shrinks — delete them:\n` +
        `${stale.map(describe).join("\n")}\n  bin/clone-gate --prune-baseline`,
    );
  }
  if (carried.length > 0) {
    // Still a finding — the committed baseline disagrees with the tree, and this run writes nothing.
    // What it is not is a choice between two impossible things, which is what #282 hit: the same
    // debt reported as both paid off and newly introduced, with prune only able to delete.
    console.error(
      `clone gate: ${carried.length} baselined clone(s) were re-cut — the same code, in the same files, reported over a\n` +
        "different span of text: a comment inside it was reworded, or content beside it became shared and the\n" +
        "match grew through it. Nothing was deduplicated and nothing new was written. The baseline substitutes\n" +
        "the new fingerprint for the old, one entry for one:\n" +
        `${carried.map(describeCarry).join("\n")}\n  bin/clone-gate --prune-baseline`,
    );
  }
  if (introduced.length > 0 || stale.length > 0 || carried.length > 0) return 1;

  console.log(`clone gate: ${duplicates.length} clone(s), all carried by ${BASELINE_RELATIVE_PATH} (${baseline.length} entries)`);
  return 0;
}

/** What one call to `repairAcceptanceBaseline` decided. */
export type AcceptanceRepairOutcome =
  | { verdict: "clean" }
  | { verdict: "repaired"; added: number; carried: number }
  | { verdict: "refused"; reason: string };

/**
 * The one baseline write this gate allows itself outside `--seed-baseline`, and the mechanism
 * `.Workflow/agent-workflows/acceptance/land-gate.ts` calls before the acceptance lane pushes to
 * `main`.
 *
 * `tests/acceptance/` is immutable to every pull request (`docs/agents/clone-gate.md`'s `IMMUTABLE_SET`
 * reasoning, ADR-0053) — lane 04 is the only writer that will ever touch it, on its own separate
 * runs, from the spec alone. So a clone introduced entirely between files under `testDir` can never
 * be somebody else's to dedupe; it is lane 04's own overlap
 * (`acceptance.ts`'s `sharedTestFiles` doc names the shape: two fixtures authored on different
 * tickets that each reach the same probe the same way). Recording it in the baseline is arithmetic
 * the file set already answers, not a judgement — the ADR-0110 line between a decision and a
 * repair. A clone naming any file *outside* `testDir` is a real one, and this refuses the whole
 * batch rather than baselining the acceptance-only entries and hoping — CONTEXT.md's **Gate
 * bypass** is defined by what reached `main`, not by how much of the batch was fixable.
 *
 * Never used by `bin/clone-gate` itself: `--seed-baseline` refuses to add to a non-empty baseline
 * (see its own comment, below), because a later run absorbing whatever is there now is exactly the
 * silent widening rule 5 exists to forbid. This function bypasses that refusal on purpose, for the
 * one caller with a machine-checkable reason — every location on both sides of the clone under a
 * directory nobody but this lane may ever edit — that a human reviewing `--seed-baseline`'s refusal
 * would accept on sight.
 */
export function repairAcceptanceBaseline(root: string, testDir: string): AcceptanceRepairOutcome {
  const { files, undeclared } = scopeOf(root);
  if (undeclared.size > 0) {
    return { verdict: "refused", reason: refusal(undeclared) };
  }

  const { duplicates, analyzed } = scan(root, files);
  const { unread } = unreadFiles(root, files, analyzed);
  if (unread.length > 0) {
    return { verdict: "refused", reason: unreadRefusal(unread) };
  }

  const { baseline, introduced, stale, carried, corrupt } = baselineDiff(root, duplicates);

  if (corrupt.length > 0) {
    return { verdict: "refused", reason: corruptRefusal(corrupt) };
  }

  if (introduced.length === 0 && stale.length === 0 && carried.length === 0) {
    return { verdict: "clean" };
  }

  if (stale.length > 0) {
    // This repair only ever adds (mirroring rule 5's "only ever shrinks" from the other direction) —
    // a stale entry needs `--prune-baseline`, a human decision about debt that was paid off, not
    // something a push-time repair should silently delete on its way past.
    return {
      verdict: "refused",
      reason:
        `clone gate: ${stale.length} baseline entr(ies) no longer reproduce. This repair only ever adds — run bin/clone-gate --prune-baseline:\n` +
        stale.map(describe).join("\n"),
    };
  }

  const outside = introduced.filter((entry) => !entry.where.every((loc) => loc.startsWith(testDir)));
  if (outside.length > 0) {
    return {
      verdict: "refused",
      reason:
        `clone gate: ${outside.length} clone(s) not in the baseline touch a file outside ${testDir} — ` +
        `this run may not baseline them, and must not push a red tree:\n${outside.map(describe).join("\n")}`,
    };
  }

  // `prunedBaseline` with nothing stale to drop: the substitution half only, so a clone of this
  // lane's own that jscpd re-cut keeps its one entry instead of wedging the push the way #282
  // wedged a workstation. Nothing is deleted here and nothing is added but `introduced`.
  writeBaseline(root, [...prunedBaseline(baseline, duplicates, [], carried), ...introduced]);
  return { verdict: "repaired", added: introduced.length, carried: carried.length };
}

// --- CLI -------------------------------------------------------------------------------------
//
// `bin/clone-gate`                    scan; red on a clone the baseline does not carry.
// `bin/clone-gate --seed-baseline`    write the baseline once, at turn-on. Refuses if one exists.
// `bin/clone-gate --prune-baseline`   drop entries that no longer reproduce, and carry the ones the
//                                     detector re-cut. Never more entries out than in.
//
// `pathToFileURL(process.argv[1])` rather than a hand-built `file://` — this repo's own checkout
// path has a space in it, and the naive form loses the percent-encoding.
const isMain = process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href;

if (isMain) {
  const args = process.argv.slice(2);
  const root = args.find((arg) => !arg.startsWith("--")) ?? process.cwd();
  process.exit(runCloneGate(resolve(root), args));
}
