import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { CheckContract, probe } from "./check-contract.ts";

/**
 * The contract generator (spec #117, ADR-0056: "the contract is generated by probing the repo, and
 * a `null` it writes is a `null` it measured"). This file owns the one formatting decision and the
 * one filesystem location a generated contract needs; the actual measurement is `check-contract.ts`'s
 * `probe`, which this module never re-implements.
 *
 * `bin/gauntlet push` is the standing check ADR-0056 calls for — "the standing check is then
 * `regenerate && diff`" — invoking this file's `diff` CLI mode so a repo that has grown a check
 * since its contract was last written goes red instead of quietly lying about itself.
 */

/** Where a root's check contract lives, relative to its own tree. */
export const CONTRACT_RELATIVE_PATH = ".claude/contract.json";

/**
 * Serializes a `CheckContract` the way it is committed: two-space indent, trailing newline. The
 * one formatting decision this file owns, so the generator and a committed file can disagree only
 * on content, never on whitespace.
 */
export function serializeContract(contract: CheckContract): string {
  return `${JSON.stringify(contract, null, 2)}\n`;
}

/** Probes `root` and returns the text that belongs at `<root>/.claude/contract.json`. */
export function generateContract(root: string): string {
  return serializeContract(probe(root));
}

/** Probes `root` and writes the result to `<root>/.claude/contract.json`. */
export function writeContract(root: string): void {
  writeFileSync(join(root, CONTRACT_RELATIVE_PATH), generateContract(root));
}

/**
 * Fields, by slot, where a fresh probe of `root` disagrees with `committedPath`'s content —
 * `diffContract`'s human-readable half. Kept separate from the byte comparison the CLI actually
 * gates on, because a byte diff is what `regenerate && diff` means and a field-by-field readout is
 * only for the person who has to fix it.
 */
function describeMismatch(committedText: string, freshText: string, root: string): string {
  const lines = [
    `stale against a fresh probe of ${root} — the committed contract no longer matches what the`,
    "repo actually contains. Regenerate it:",
    `  node .Workflow/agent-workflows/shared/generate-contract.ts ${root}`,
    "",
  ];

  try {
    const committed = CheckContract.parse(JSON.parse(committedText));
    const fresh = CheckContract.parse(JSON.parse(freshText));
    for (const name of Object.keys(fresh) as Array<keyof CheckContract>) {
      for (const field of ["cmd", "why"] as const) {
        const before = committed[name][field];
        const after = fresh[name][field];
        if (before !== after) {
          lines.push(`${name}.${field}:`);
          lines.push(`  committed:    ${JSON.stringify(before)}`);
          lines.push(`  fresh probe:  ${JSON.stringify(after)}`);
        }
      }
    }
  } catch {
    // The committed file is not even a valid CheckContract — the byte diff below is the whole
    // story, and a field-by-field readout would just be a second, worse way of saying that.
    lines.push("--- committed ---", committedText, "--- fresh probe ---", freshText);
  }

  return lines.join("\n");
}

/**
 * `regenerate && diff` (ADR-0056), as one call: probes `root` fresh and compares it byte-for-byte
 * against whatever text already sits at `committedPath`. Returns `undefined` when they match, or a
 * human-readable report of the mismatch when they don't — never throws on a mismatch, since that is
 * the expected, well-formed result of a repo that has drifted from its own contract.
 */
export function diffContract(root: string, committedPath: string): string | undefined {
  const fresh = generateContract(root);
  const committed = readFileSync(committedPath, "utf8");
  if (fresh === committed) return undefined;
  return describeMismatch(committed, fresh, root);
}

// --- CLI -------------------------------------------------------------------------------------
//
// `node generate-contract.ts <root>`             regenerates <root>/.claude/contract.json in place.
// `node generate-contract.ts diff <root> <path>`  exits 1 and prints the mismatch when <path>
//                                                  disagrees with a fresh probe of <root>, exits 0
//                                                  when they match. This is the mode `bin/gauntlet
//                                                  push` runs.
//
// Guarded with `pathToFileURL(process.argv[1])`, never a hand-built `file://${argv[1]}` — the
// latter loses percent-encoding on a path with a space, which is this repo's own real checkout
// path, and would make this guard silently never fire there.
const isMain =
  process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href;

if (isMain) {
  const args = process.argv.slice(2);
  if (args[0] === "diff") {
    const [, root, committedPath] = args;
    if (!root || !committedPath) {
      console.error("usage: generate-contract.ts diff <root> <contractPath>");
      process.exit(2);
    }
    const mismatch = diffContract(root, committedPath);
    if (mismatch) {
      console.log(mismatch);
      process.exit(1);
    }
    process.exit(0);
  } else {
    const root = args[0] ?? process.cwd();
    writeContract(root);
  }
}
